### PR TITLE
Correctly create or update the restricted login proctor password

### PR DESCRIPTION
**Pull request by drgrice1**
There was logic error that made the `if/else` statement fall through incorrectly.  The conditions of a nested `if` were condensed into the first condition of the `if/else` statement.  This puts it back to the way it was with a nested `if`.

This fixes issue #2146.

### CODE REVIEW

**Review by Alex-Jordan — APPROVED** [review]
Thanks for figuring this out. This change works for me.

**Comment by Alex-Jordan** [comment]
Maybe since it is so close after the release and this is a bug, we go ahead and merge rather than wait for a third approval? Or I can tag @pstaabp to maybe give it a quick look.

**Comment by drgrice1** [comment]
Yeah, that should be fine.

**Comment by somiaj** [comment]
Do we another PR for develop for this then?

**Comment by drgrice1** [comment]
@somiaj: I have it ready. I will add it later.

**Pull request merged**
