### PR TITLE
Fix the OverrideSiteURL in the code.

### PR DESCRIPTION
**Pull request by drgrice1**
Somehow, when I changed the variable in the config file, I didn't also change the variable in the code.

### CODE REVIEW

**Review by Alex-Jordan — APPROVED** [review]
This is good. But see the discussion at #2074. I'm not sure this is a good way to handle overriding the path in most cases. The config variable might need to be something different for each course, for each ELT/app link from the LMS.

**Comment by drgrice1** [comment]
Each course can set the variable to a different value in the course.conf file.  If the only need is to change http to https, that can be accomplished by the config variable.  There is no need for a code reference.  Generally, we need to move away from using such things in the config at all.  Eventually (webwork3) there will be none of that allowed.

**Comment by Alex-Jordan** [comment]
I'd like to have a way to handle this site-wide. I don't want to manage all the courses' config files for this.

These URLs are more complicated when there is homework grade passback, or an instructor wants the student to go directly to a particular page from the URL. So in that situation there is no one single value you can use for this config variable. Unless the OAuth is truncating those URL paths anyway down to just the course?

**Comment by drgrice1** [comment]
Regardless of any further improvements that you may desire, this pull request should go through for now.  It obviously is needed.  If you want further improvements for your use case, then I suggest that you submit a pull request.  I don't know what you need.

**Comment by Alex-Jordan** [comment]
Agreed, that's why I approved this already.

**Comment by drgrice1** [comment]
Sorry, I didn't see the approval.

**Review by pstaabp — APPROVED** [review]

**Pull request merged**
