### PR TITLE
updated version

### PR DESCRIPTION
**Pull request by pstaabp**
Updated the version # and copyright dates.

### CODE REVIEW

**Review by taniwallach — APPROVED** [review]
This should probably be merged at the "very end" after all updates to the `WeBWorK-2.16` branch get merge into `develop`, and before it gets merged into `master`.

**Comment by drgrice1** [comment]
There is more that needs to be done here as well.  The branch names need to be changed in the Dockerfile.  I have added a pull request to this one for that.

I have a plan for this that will make it so that the develop and master branch don't have the issues from the last release.  That being that if someone originally works on the master branch and then creates a pull request that targets the develop branch, then there was a massive list of commits that were attempted to be added to the develop branch.  This plan requires that all changes to master be done first.  That includes the version and Dockerfile changes.  Then the WeBWorK-2.16 branch will be merged into master.  Then the VERSION and Dockerfile changes will be changed to develop.  Then the WeBWorK-2.16 will be merged into develop.  This ensures that the develop branch progresses appropriately after the master branch and fixes the issues from before.

With this plan this pull request can and should be merged now (and the Dockerfile updated as well for proper testing there -- @pstaabp: I have added a pull request to this pull request branch for that, so please merge that).

**Comment by drgrice1** [comment]
I have updated my plan.  The part described is still the same, but I am also keeping develop and WeBWorK-2.16 in sync (as well as PG-2.16).  This is easiest if this is not merged yet.

**Comment by taniwallach** [comment]
> I have updated my plan. The part described is still the same, but I am also keeping develop and WeBWorK-2.16 in sync (as well as PG-2.16). This is easiest if this is not merged yet.

Avoiding the mess created using the approaches from recent releases including 2.15 would be a great thing.

Please share/document the details of the desired workflow  - so "we" all know the approved workflow for the 3 branches until the 2.16 release, and then for how hotfixes to master should be handled.

**Pull request closed without merging**
