### PR TITLE
Show set header in proctored login.

### PR DESCRIPTION
**Pull request by somiaj**
Use the set header for the page info-box when at a login prompt for a proctored gateway quiz instead of showing the site info or login info.

### CODE REVIEW

**Review by drgrice1 — APPROVED** [review]
The code looks good (although could perhaps be perltidied!).

I think this makes more sense than showing the site info and login info on this page.  However, since this was implemented this way, it may be that there are those that think otherwise.

**Comment by drgrice1** [comment]
Actually, thinking about it more, I forgot that set headers were not used for gateway quizzes before.  So that is probably why the site info was shown.  Now that the set header is used for gateway quizzes this makes more sense.

**Comment by somiaj** [comment]
Removed an unused variable in my code, and ran perltidy on the whole file.

**Review by pstaabp — APPROVED** [review]

**Comment by drgrice1** [comment]
@somiaj:  Note that this pull request will need some changes now that the #1792 has been merged.  See line 242 of lib/WeBWorK/ContentGenerator/ProblemSet.pm for the new correct way to call `WeBWorK::PG->new`.

**Review by drdrew42 — APPROVED** [review]

**Pull request merged**
