### PR TITLE
Add Rserve and required modules to the safe module list

### PR DESCRIPTION
**Pull request by cubranic**
Companion request to openwebwork/pg#214

### CODE REVIEW

**Comment by goehle** [comment]
You might add some conifuration information to localOverrides.conf.dist.  Basically something like 
```
# This is configuration for the Rserve pg module.  More explanation about configuration and
# setting up your own Rserve server.  Blah Blah Blah
# $pg{specialPGEnvironmentVars}{Rserve} = {host => "localhost"};
```
to help people get started.

**Comment by cubranic** [comment]
@goehle Is it OK to point to my university's wiki? Or would you rather that information were on the MAA wiki?

**Comment by goehle** [comment]
I suppose I would like stuff on the MAA wiki, but I would also like it to be up to date. So if your university wiki is more likely to have current information you should use that.

**Comment by Alex-Jordan** [comment]
When I switch to develop branch now, I get these perl warnings on pages:

```
    Failed to evaluate module Rserve: Can't locate Rserve.pm in @INC (you may need to install the Rserve module) (@INC contains: /opt/webwork/pg/lib /opt/webwork/webwork2/lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl . /etc/apache2) at (eval 749) line 1.
    Failed to evaluate module Class::Tiny: Can't locate Rserve.pm in @INC (you may need to install the Rserve module) (@INC contains: /opt/webwork/pg/lib /opt/webwork/webwork2/lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl . /etc/apache2) at (eval 749) line 1.
    Failed to evaluate module IO::Handle: Can't locate Rserve.pm in @INC (you may need to install the Rserve module) (@INC contains: /opt/webwork/pg/lib /opt/webwork/webwork2/lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl . /etc/apache2) at (eval 749) line 1.
```

The way I usually install packages is using MCPAN, but it doesn't know what `Rserve` is when I try `install Rserve`. How can I install this Rserve package?

**Comment by mgage** [comment]
That's what you need to work with the R server.  You can comment it out in defaults.config.   We should do that for vthe release
.



On Jun 24, 2017 7:53 PM, Alex Jordan <notifications@github.com> wrote:

When I switch to develop branch now, I get these perl warnings on pages:

    Failed to evaluate module Rserve: Can't locate Rserve.pm in @INC (you may need to install the Rserve module) (@INC contains: /opt/webwork/pg/lib /opt/webwork/webwork2/lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl . /etc/apache2) at (eval 749) line 1.
    Failed to evaluate module Class::Tiny: Can't locate Rserve.pm in @INC (you may need to install the Rserve module) (@INC contains: /opt/webwork/pg/lib /opt/webwork/webwork2/lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl . /etc/apache2) at (eval 749) line 1.
    Failed to evaluate module IO::Handle: Can't locate Rserve.pm in @INC (you may need to install the Rserve module) (@INC contains: /opt/webwork/pg/lib /opt/webwork/webwork2/lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl . /etc/apache2) at (eval 749) line 1.


The way I usually install packages is using MCPAN, but it doesn't know what Rserve is when I try install Rserve. How can I install this Rserve package?

**Comment by cubranic** [comment]
It's Statistics::R::IO (https://metacpan.org/pod/Statistics::R::IO)

**Comment by Alex-Jordan** [comment]
OK, the `Rserve` package I am "missing" is in the develop branch of pg. That was my issue; I had only moved webwork2 to develop, not pg.

**Pull request merged**
