### PR TITLE
Replace \1 by  in Utils.pm

### PR DESCRIPTION
**Pull request by mgage**
Replaces \1 by $1 in one grep expression

### CODE REVIEW

**Comment by goehle** [comment]
What does this change do, OOC?

**Comment by mgage** [comment]
This and the similar change in PG  converts from an old perl paradigm to a new one

s/(foo.)/\1bar/    would replace  foo3 by foo3bar in a string and it would replace foo7 by foo7bar.     This method is deprecated and creates lots of 
warning messages in the log (for new versions of perl)

The new way to write this is
s/(foo.)/$1bar/       the contents of $1 is replaced by what is captured in the first set of parentheses. 

(My example is overly simple -- normally you'd have a more complicated matching pattern.)

**Comment by goehle** [comment]
I dont think this one should be changed either, since its also matching a back reference.

Now, I'm not sure this function is used anywhere but when I inserted some test code (shown below) it didn't properly dequote the @ unless the \1\2 was used in place of $1$2
```
	my $poem = <<POEM;
@     Now far ahead the Road has gone,
@        And I must follow, if I can, ``
@     Pursuing it with eager feet,
@        Until it joins some larger way...
@           --- Bilbo
POEM
die(dequote($poem));
```

**Comment by dpvc** [comment]
I agree, these should remain `\1\2` or you will get substitution of the *previous* values of `$1` and `$2` into the match string (whatever they were from the last match, if there was one, or empty strings otherwise).

**Comment by mgage** [comment]
You're right.  I'm withdrawing this pull request.  Only the \1 on the right side of a substitution
string should be changed to $1.   Those are the ones causing the warnings.  The back references in
matches and on the left side of substitution strings must remain as \1.    

Sorry about that -- I'd forgotten the difference.

-- Mike

**Pull request closed without merging**
