### PR TITLE
Add support for a 2 stage Docker build process + support graceful Apache restart

### PR DESCRIPTION
**Pull request by taniwallach**
Docker improvements:

1. Add files for a 2 stage Docker build process.
2. Set things up so Apache gets stopped "gracefully" (current requests get completed).
  - https://httpd.apache.org/docs/2.4/programs/apachectl.html
  - Also, it is now possible to do `docker container exec -it webwork2_app_1 /usr/sbin/apachectl graceful`:
    - This is a faster restart if code is mounted from outside the container.
    - It should also help with log rotation.
3.   Also some minor fixes.

---

### 2 stage build process

```
# cd into webwork2 directory (as usual)
docker build --tag webwork-base:forWW216 -f DockerfileStage1 .
vim docker-compose.yml
# uncomment the line
#    dockerfile: DockerfileStage2
docker-compose build
```

The first stage does all the OS level work, and involves installing several hundred ubuntu packages (and some CPAN Perl packages), so takes quite some time.
The second stage installs WeBWorK, and is relatively fast.

---

### Force rebuild of OS later
```
# cd into webwork2 directory (as usual)
docker build --no-cache --tag webwork-base:forWW216 -f DockerfileStage1 .
```

### CODE REVIEW

**Review by drgrice1 — APPROVED** [review]
This looks good.  I have tested the build steps and it works.  There is an issue with the permissions on htdocs/tmp with the default build that needs to be resolved.

**Comment by mgage** [comment]
the htdocs/tmp permission issue  is addressed in my upcoming pull request to patch the 2 stage docker process.

**Comment by drgrice1** [comment]
> the htdocs/tmp permission issue is addressed in my upcoming pull request to patch the 2 stage docker process.

I see that. I see that you did it without the recursive flag as suggested.

**Comment by taniwallach** [comment]
Note: this PR does not fix the `sed` code for creating `site.conf` which no longer properly sets the database password, as the `site.conf.dist` was fixed in https://github.com/openwebwork/webwork2/pull/1399 to use single quotes on the password, but `docker-config/docker-entrypoint.sh` was not yet fixed to handle that change. That is among the several things fixed in https://github.com/openwebwork/webwork2/pull/1433.

**Comment by drgrice1** [comment]
I will go ahead and merge this unless someone objects.  It only affects the docker build, and seems to work well for that aside from the mentioned issues that are fixed in @mgage's pull request.

**Comment by mgage** [comment]
I'm in favor of merging this PR.  It will make it easier for me to organize the additional minor changes I'd like to add.

**Review by mgage — APPROVED** [review]

**Pull request merged**
