### PR TITLE
Fix to iteration over GWQ problems in case of missing numbers

### PR DESCRIPTION
**Pull request by mikeshulman**
See #899.

### CODE REVIEW

**Comment by taniwallach** [comment]
The fix probably enables access. However, there may be additional issues, as there are indications in the discussion at https://webwork.maa.org/moodle/mod/forum/discuss.php?d=4932 that this issue may occur when a user's gateway assignment data is not consistent with the main quiz definition. 

If merging this could lead to a student being able to open a quiz which is not what they should be getting - then maybe leaving the error message is a better approach, as it would force an unassign + renumber + reassign to fix the problem and get the student the "correct" assignment data.

**Comment by drgrice1** [comment]
I> The fix probably enables access. However, there may be additional issues, as there are indications in the discussion at https://webwork.maa.org/moodle/mod/forum/discuss.php?d=4932 that this issue may occur when a user's gateway assignment data is not consistent with the main quiz definition.

The issues in that forum discussion are not caused by the issue that this fixes.  User assignment data not matching the main definition is a problem that occurs for both homework assignments and gateway quizzes, and is another issue.

> If merging this could lead to a student being able to open a quiz which is not what they should be getting - then maybe leaving the error message is a better approach, as it would force an unassign + renumber + reassign to fix the problem and get the student the "correct" assignment data.

Merging this will not give students access to quizzes that they should not have access to.  That is enforced by permissions, and is unrelated to this.  It should never be the case that an assignment is assigned to a student, and yet some problems in that assignment are not.

**Comment by drgrice1** [comment]
> If merging this could lead to a student being able to open a quiz which is not what they should be getting - then maybe leaving the error message is a better approach, as it would force an unassign + renumber + reassign to fix the problem and get the student the "correct" assignment data.

To add more to what I have already said, note that this does not have anything to do with the student data not matching the assignment data.  The fact is the data does match.  However, there is an indexing issue that is fixed by this pull request that causes an error for everyone that the set is assigned to.  No amount of unassigning and reassigning, or exporting and importing will fix this.  The only thing that will is making the problems be numbered consecutively (until this pull request is merged).  It doesn't make any sense to create a quiz and assign it to students that will never work, and to say that it is valid to do so to prevent students from accessing it is really crazy.  Don't assign it, or make it not visible.

**Review by taniwallach — APPROVED** [review]
OK - got it. I thought about the changes made here, and they certainly make sense.
I have been convinced that the issues caused by editing assignments which have collected student data which can get messed up should not hold this PR back.
I did not test myself, and am relying on the test by @drgrice1 .

**Comment by drgrice1** [comment]
I think this can be merged.  I am going to do so unless there is an objection.

**Pull request merged**
