### PR TITLE
Always send feedback emails to those in the `$mail{feedbackRecipients}` list.

### PR DESCRIPTION
**Pull request by drgrice1**
This is how this was in previous versions of webwork2.  Restructuring of things to clean up how the email recipient list is generated resulted in this being dependent on the `$permissionLevels{receive_feedback}` setting.

To test this go to the E-Mail tab in the course configuration and uncheck all of the check boxes for the "E-mail feedback from students automatically sent to this permission level and higher" setting, and add an email address to the "Additional addresses for receiving feedback e-mail" setting.  With develop or main when you click on the feedback buttons on a homework set or problem page it will show "No e-mail recipients are listed for this course."  With this pull request the email address you add will be shown.

### CODE REVIEW

**Review by pstaabp — APPROVED** [review]
Fixes the issue.

**Review by Alex-Jordan — APPROVED** [review]

**Comment by Alex-Jordan** [comment]
Did this fix a bug such that it needs a hotfix version?

**Comment by drgrice1** [comment]
It did fix a bug as described in the initial comment of this pull request.  It is perhaps not that serious though (or maybe it is).  If there are no permission levels set for the "receive_feedback" permission or that only contains "nobody", then the `$mail{feedbackRecipients}` list is ignored entirely (due to the `fetchEmailRecipients` method returning earlier in the code).

If you think a hotfix is justified, I am good with that.

**Comment by Alex-Jordan** [comment]
I merged #2192 (into main) and then this one (into develop) just seemed to automatically merge. Not sure if I messed something up.

**Comment by drgrice1** [comment]
Didn't @pstaabp already merge this previously?

**Comment by Alex-Jordan** [comment]
Oh, I see. I assumed they were both unmerged together.

**Comment by drgrice1** [comment]
Yeah, this was merged earlier, and then you asked if this fixed a but that merited a hotfix, and so I opened the hotfix pull request.  So no mistakes were made!

**Pull request merged**
