### PR TITLE
Release 2.11 Pull Request

### PR DESCRIPTION
**Pull request by goehle**
This is the master pull request for Release 2.11.  The major changes in this release are: 

## WeBWorK
-  Just In Time Homework Assignments  - This adds the just in time homework assignment type.  This is an “adaptive” style homework meant to provide just in time review to homework problems.  (This is an important new feature with many possible uses: see Geoff Goehle’s descriptive overview.  )
-  Embedding WeBWorK problems in webpages using iframes. (See Mike Gage’s blog post.) This has potential for many uses and is being developed further by Rob Beezer, Alex Jordan, Mike Gage and Geoff Goehle.
-  LTI Changes - upgrades to the LTI authentication module including more debugging and support for server wide configuration.  LTI allows interoperability between WeBWorK and LMS such as Blackboard, Moodle or Sakai. (Moodle also has a more customized bridge to WeBWorK:  wwassignment  connects assignments and opaque_server connects individual WeBWorK questions )
-  Tweaks for 2.11 - A number of tweaks for 2.11.  The largest of which is that professor level users do not have permission to change course.conf anymore.  Instead only admin level users can change that file.  This can be disabled serverwide, or an admin user added to a class can change the permission level of the professors to admin to allow course.conf editing.
-  WebworkClient Local Storage   and js for iframe-resizer  - General upgrades to the xmlrpc rendering pathway including support for embedding problems in webpages, local persistance of problem scores and math xml problems.  
-  Remove TZ from Date Entry  and DateTime refactor and Friends - Dates in webwork no longer require a time zone when entered.  Instead the server will assume the dates are in whatever time zone is specified for the class.  The date time picker script was refactored and generally improved.  
Icons in LB1 to signal problems with math objects and static problems - There are now icons in the library browser to help signify when problems use math objects and when problems don’t have any randomization.  
-  Set defs search depth  - set definition files can now be stored in subdirectories in the templates directory.  
-  Develop wwsh  - wwsh no longer operates as an interactive shell.  Instead the wwsh command can be used to run prewritten scripts, several of which have been included.  
-  Bugs and Small Changes
  -  Editor Tweaks 
  -  Add path to new macro files from Hope 
  -  Math 4 Javascript upgrades 
  -  Improve tagging menu system 
  -  DB Key Prefix Length 
  -  User Detail Bug 
  -  Develop fix null password 
  -  XSS Fix 
  -  Remove warning that cookie userID and sessionID do not match. 
  -  Radio/Math4 Bug 
  -  Classlist Export Bug 
  -  SendMail Bug
  -  Set defs search depth 
  -  Fix the way WeBWorK rounds scores.
  -  Scoring Multiple Select Bug 
  -  Apache Version Conf Variable 
  -  Add library tag RESOURCES
  -  Mathview Accessibility

## PG

-  Opaqueserver mods - Modifications to PG to allow for the Moodle WeBWorK Question type
-  Javascript LiveGraph Replacement - a replacement for the java based 3d grapher.  The new 3d grapher is js/webgl based.  3D graphics returns!  See Geoff Goehle's blog post for details.
-  Create contextTrigDegrees.pl - a new context which causes all trig functions to operate in degrees mode.  
-  Bugs and Small Changes
  -  modifications for AskSage 
  -  Develop grep fix 
  -  Develop fix pretty print 
  -  Add zero height paragraph break to html at start of problems 
  -  Add new macro $BRBR and added nbsp, ndash, and mdash to character display macros 
  -  Make hardcopy properly handle opened sections. 
  -  Allow PGalias to make an alias for a pdf file in HTML type modes. 
  -  Make named answer rules work properly with MathObject answers in PGML colspan for table cells; cell-specific halign 
  -  Popup menus and Radio buttons 
  -  Create unique UUID for graphs created on the fly
  -  IO Cleanup 
  -  Fix problem with alternate decimals

### CODE REVIEW

**Comment by goehle** [comment]
This is the checklist of things which need to be done before we release 2.11
-  [ ] Test installer. 
-  [ ]  Write 2.11 release notes, including the appropriate wiki page. 
-  [ ] Test release 2.11 using the testing checklist.

**Comment by NeilHanlon** [comment]
Is this release considered stable?

When can we look for this being merged into master?

(Doing some webwork upgrades in a week (OS+OPL) and was wondering if we should upgrade the system, as well.

**Comment by goehle** [comment]
I've been running through our testing protocols and writing up the release notes for this.  It *should* be released in the next couple weeks.  Its also finals right now so its tough to juggle both things.  

You could upgrade to the release-2.11 branch and very little would change between now and when it gets into master.  There is going to be another bugfixing pull request with some typos and other small things, but overall its stable.

**Comment by NeilHanlon** [comment]
Totally—I understand.

 

Just finished up finals myself haha

 

I think we’ll wait until it’s in master. I might deploy 2.11 to our development server for the math department to test.

**Comment by NeilHanlon** [comment]
Just one more question--

What do the LTI improvements mean? Is there now additional functionality for LMS'?

**Comment by goehle** [comment]
The general LTI improvements are all centered around authentication.
Things have been polished so that LTI based authentication is easier to set
up and easier to diagnose when things go wrong.  So the use case for this
would be that you would include links to WeBWorK or individual WeBWorK sets
in an LMS like Blackboard and students could click the link and be taken
right into WeBWorK.  However it doesn't support transferring grades between
the two systems or anything like that.  If you want that kind of
interoperability you will need Moodle, which has several nice ways to talk
to WeBWorK.

**Pull request merged**
