### PR TITLE
Czech translation (student's interface)

### PR DESCRIPTION
**Pull request by robert-marik**
Translation of most texts visible for student. Allows to work comfortably with the system when doing homeworks.
The texts for teacher and admin are kept in English in order stay in touch with community and follow better community hints and suggestions.

### CODE REVIEW

**Comment by taniwallach** [comment]
Please split the 2 commits into different pull request. I think the UTF-8 patch for achievements should be handled separately from the addition of the Czech translation file, so that the "history" in Git is clear.
Please create the new pull requests from the **develop** branch. I do not think there is any need to make either fix a hot-fix for the current WW 2.15 (master branch). Expert users who need do not want to run the develop branch and want these fixes either before WW 2.16 can certainly handle making the necessary changes to a local server.

**Review by taniwallach — CHANGES_REQUESTED** [review]
Request to base of develop, and split into 2 different PRs.

**Comment by robert-marik** [comment]
Thank you for the suggestions. I will prepare new patches according to your instructions.

**Comment by robert-marik** [comment]
Will prepare new pull requests as suggested.

**Pull request closed without merging**
