### PR TITLE
Update the localization files one last time before the release.

### PR DESCRIPTION
**Pull request by drgrice1**
This should be the last time.  The remaining pull requests that might go in don't change strings.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Do you want to fold in deleting:
https://github.com/openwebwork/webwork2/blob/WeBWorK-2.16/lib/WeBWorK/Localize/tr.bak
?

Seems like an accidental commit from 10 years ago.

**Comment by drgrice1** [comment]
I added the removal of that file to this pull request.  Good clean up observation.

**Comment by pstaabp** [comment]
How do I test this?  I can take a look at this today.

**Comment by drgrice1** [comment]
There probably isn't that much testing really needed.  I just run the script update_localization_files and commit the resulting changes.  This is something that we will integrate with some service like Transifex and automate in the future.

**Review by taniwallach — APPROVED** [review]
This is mainly automatically generated changes and should be merged before the formal announcement of the release candidate.

**Comment by Alex-Jordan** [comment]
Is the process for updating translations as simple as manually going through a `.po` file and committing edits?

I might take a stab at Hungarian. I have a polyglot in the family who could sit with me and do German, French, Spanish, and possibly Portuguese. None of us are native speakers and specific vocabulary for computer use and navigating a website might not quite fit, but it may be better than nothing.

Or we could reach out to the people who committed previously to these files.

**Comment by taniwallach** [comment]
> Is the process for updating translations as simple as manually going through a `.po` file and committing edits?

At present - yes. In principle - we should sync the current status into Transifex, and make sure to keep the code-base and Transifex in sync, and then translation fixes/changes can be done in the Transifex website, and easily brought into the code-base.

Someone figuring out a good and efficient approach to sync with Transifex would be a great step forward.

> I might take a stab at Hungarian. I have a polyglot in the family who could sit with me and do German, French, Spanish, and possibly Portuguese. None of us are native speakers and specific vocabulary for computer use and navigating a website might not quite fit, but it may be better than nothing.

I would say that effort should be focused on languages where there is expressed current interest, or potential interest, and at least be done in cooperation with users/potential users.

@mgage probably recalls more details of who is using WW in non-English languages.
  - There is a team of people who were working on the Spanish translations (@enriqueacosta and others) - focused on the student side and intentionally leaving the instructor side in English. 
  - There are French language sites in Canada (@jutrembBDEB, https://github.com/CCDMD/webwork2_fr_qc/) who could probably help update the French translation files. 
  - @heiderich was using WW in Germany.

> Or we could reach out to the people who committed previously to these files.

We had planned to try to reach out to prior contributors to the translations once the release candidate was "final". I would suggest we see if we can make it possible to work with both Transifex and the `.po` files.

**Pull request merged**
