### PR TITLE
Remove dragmath - Just a little clean up

### PR DESCRIPTION
**Pull request by drgrice1**
We no longer support this, and it is no longer used.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Should this also remove the folder `htdocs/dragmathedit`?

**Comment by drgrice1** [comment]
Yes, it probably should.  I missed that.

**Comment by Alex-Jordan** [comment]
As long as I was looking here....

Do these three things do anything, and should they be cleared too?
```
$pg{specialPGEnvironmentVars}{MathView} = 0;
$pg{specialPGEnvironmentVars}{WirisEditor} = 0;
$pg{specialPGEnvironmentVars}{MathQuill} = 0;
```

Instead of these booleans, there is `$pg{specialPGEnvironmentVars}{entryAssist}`.

I will merge this either way. But I'll wait to discuss this last thing I just brought up.

**Comment by drgrice1** [comment]
I don't think they are used.  I didn't remove those as they are not related to dragmath.  This may be a point to mention on @dlglin's pull reqest #1247.

**Pull request merged**
