### PR TITLE
Patch for docker two stage

### PR DESCRIPTION
**Pull request by mgage**
this includes commits in @taniwallach 's " docker-two-stage-build.... "  -- I didn't have permission to submit a pull request directly to tani's github repos.

### CODE REVIEW

**Comment by mgage** [comment]
this includes @taniwallach repos "docker-two-stage...." branch

added instructions for creating a webwork docker box with minimal configuration (out of the box)
www-data is made owner of webwork2/htdocs/tmp to prevent errors when creating courses
added  vim and less to ADD_APT_PACKAGES

don't run 
       #$WEBWORK_ROOT/bin/upgrade_admin_db.pl
        #$WEBWORK_ROOT/wwsh admin ./addadmin
running upgrade_admin_db.pl may not be necessary -- although I think if the admin tables are not up todate  it might cause trouble with running the admin course

**Comment by taniwallach** [comment]
If you are enabling the 2-stage build process as the default, then the instructions need to tell the user to run
`docker build --tag webwork-base:forWW216 -f DockerfileStage1 .` before they can run `docker-compose up` to do the second stage.

I still think that the instructions file probably belongs in some subdirectory.

**Comment by drgrice1** [comment]
Now that @taniwallach's two stage docker build pull request has been merged you should be able to clean this up a bit.  If you want to talk about how to do this well, let me know.

**Comment by mgage** [comment]
withdrawn in favor of #1435 patch5 version

**Pull request closed without merging**
