### PR TITLE
Hardcopy theme order

### PR DESCRIPTION
**Pull request by Alex-Jordan**
This is to replace #1266. 

Also, I noticed `--shell-escape` was still present. We decided this needed to go, is that right?

### CODE REVIEW

**Comment by drgrice1** [comment]
We did decide to disable that, but we were going to go with `--no-shell-escape` as that completely disables TeX's `\write18` command.  Just removing the `--shell-escape` leaves that command active, but only allows specific commands listed in the texmf.cnf file.  Also @taniwallach also has this in pull request #1160.

**Comment by Alex-Jordan** [comment]
I put `--no-shell-escape` in the three places, and put in some commentary.

**Comment by drgrice1** [comment]
Looks good.

You gave up on using PGsort?

**Review by drgrice1 — APPROVED** [review]

**Comment by Alex-Jordan** [comment]
> You gave up on using PGsort?

I did this before learning about PGsort from your comment.

**Comment by drgrice1** [comment]
Yeah, could use it like:
```perl
$hardcopyThemes = PGsort(sub { return $_[0] cmp $_[1]; }, keys(%{$hardcopyThemeNames}));
```

**Comment by drgrice1** [comment]
You don't need `return` in that.

**Pull request merged**
