### PR TITLE
Comment out pretty_print command that is causing a segmentation 11 fa…

### PR DESCRIPTION
**Pull request by mgage**
…ult (on macbook at least)

### CODE REVIEW

**Comment by mgage** [comment]
As far as I can tell this variable is never used so commenting it out should not have any effect.
If pretty print is called (i.e. it's not commented out) then when using clients/sendXMLPRC.pl or the standalonePGrenderer  or the opaque_server (see my repo on standalone renderer and the openwebwork repo on opaque_server)  a segment 11 fault is generated as the WebworkClient is used to format output.

**Comment by goehle** [comment]
Note:  This flag used to be used to indicate if a lone essay answer would be graded later. 

https://github.com/openwebwork/webwork2/blob/WeBWorK-2.11/lib/WeBWorK/ContentGenerator/Problem.pm

but the new messaging is different and no longer uses the flag.  However, the flag is stilled used for gateways

https://github.com/goehle/webwork2/blob/develop/lib/WeBWorK/ContentGenerator/GatewayQuiz.pm

so if this is ever ported over to gateways then the essayFlag will have to be removed there.

**Comment by goehle** [comment]
As an aside, this hotfix to master was not done correctly.  There should have been a single branch off of master and two pull requests, one to master on openwebwork and the other two develop on openwebwork.  By having two feature branches with the same code changes but different commit numbers there is a greater chance that conflicts will be created down the road.  This is the case here because in each branch you commented out the pretty print line in WebworkClient in a different way.  Its my fault for not noticing until after I merged, so I will fix the conflicts by pulling the "master_hotfix" branch into develop.

**Comment by mgage** [comment]
ok -- thanks for fixing this for me.

**Pull request merged**
