### PR TITLE
Develop mathquill

### PR DESCRIPTION
**Pull request by mgage**
This seems be a cleaner version of the mathquill PR #920 .  It only changes 28 files and doesn't have the massive 150 file commit.  I cherry picked the essential macquill changes directly into a fresh version of develop and then reconciled changes in 10 or so files.

### CODE REVIEW

**Comment by drdrew42** [comment]
@mgage I have some further improvements to this branch - how should I go about this?

**Comment by mgage** [comment]
I think this will work.

create a fresh branch of develop

git branch -t fresh_develop  origin/develop
git checkout develop
git pull mgage develop_mathquill (whatever my branch was called)

Now you should have exactly what my pull request is.

I’m not even sure you need to create the develop branch first.
Now add your changes, push it to your github and issue a new pull request.
I’ll close mine and your old one.

Does that seem to work?

Take care,

Mike

On Feb 1, 2019, at 12:53 PM, drdrew42 <notifications@github.com<mailto:notifications@github.com>> wrote:


@mgage<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mgage&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=C6Pt5AGtImanmAdcooarL-JZO8M5dSFPfs3VweYXYkE&m=5AztQ7mCi9yZ6cncVlZGblucC5fyrdlH3yYrJ23udls&s=grGjPztQ8dmo_lLdehamGSfsFVQhBN_LxFRCSyOLlno&e=> I have some further improvements to this branch - how should I go about this?

**Comment by drdrew42** [comment]
Okay, I'll try following this - but I've got one lingering issue that I want to clear up before I push this next collection of updates. The only updates will be to `mathquill.js` and `mqeditor.js`

**Comment by dpvc** [comment]
@mgage, I don't think this is quite the right procedure.  Andrew may not have your fork as a remote for his clone, and so he will have to set that up first.  Then the only thing he has to do it check out your copy of the branch and it will create a branch automatically for him.  Finally, your process would merge into his copy of develop, rather than the fresh_develop branch.

So I think  what he should do is something more like

```
git remote add https://github.com/mgage/webwork2.git mgage
git fetch mgage
git checkout mgage/develop_mathquill
```

this should get him a `develop_mathquill` branch that he can commit to and push.  Then he can either make a pull request to the main repo from that, or a pr to your fork if you would like to make the final PR.

**Comment by mgage** [comment]
@dpvc -- you are right -- the checkout develop was a typo which I've corrected to checkout fresh_develop in case someone else reads it.  I thought checking out develop first was not necessary but it has become a habit of mine to make sure I'm on the right branch and it is pointed at a known target (origin/develop).

Andrew go ahead and make a PR to the main repo and once that is done I will close the other PR.  This is basically your PR there is no need for me to be in the middle of it.

**Comment by mgage** [comment]
replaced by PR #922

**Pull request closed without merging**
