### PR TITLE
Fix issue #1077

### PR DESCRIPTION
**Pull request by cucucucumber**
I fixed the issue #1077 by forcing UTF-8 encoding to read and write configuration files.

**Warning:** Because of the Windows text file saving mechanism, some unexpected situations may occur on Windows Server 2012/Windows 8.1 and earlier versions. But this problem does not appear after Windows 10 Build 19041 and forced UTF-8 file encoding is turned on.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Thanks for submitting a fix. Pull requests generally need to be into the `develop` branch, not the `master` branch. That might mean that you need to rebase your work off of `develop`.

**Comment by Alex-Jordan** [comment]
I tried changing the target branch to `develop`, but what I saw indicated that is not the way to handle this.

**Comment by cucucucumber** [comment]
I have migrated the target branch to develop.

**Comment by Alex-Jordan** [comment]
The edits you made are not large, so it may be simplest to apply them from scratch on a branch that is built off of `develop`. I wish I could advise you better on using git to find a git way to get it moved, but I'm shaky on some things.

**Comment by Alex-Jordan** [comment]
Sorry, I didn't explain enough. Changing the target branch to `develop` is not enough; that is what I tried myself earlier. Now this PR has 30 commits and affects 12 files, which is not what should be happening. Also this PR has a merge conflict. It's all because even though you moved the target to `develop`, the source branch is still some offshoot of `master`, and there is enough of a difference that all this is here.

**Comment by Alex-Jordan** [comment]
So as I said two comments ago, you could make the same edits on some branch that is built off of `develop`. It may be most expedient to do that, since it is only a few lines that are edited in two files. Or you might pursue some git/GitHub approach to get your commit #165f532 into `develop`.

**Comment by drgrice1** [comment]
You will probably need to create a new branch, based off of the develop branch.  Then you can cherry pick the commit from your forks master branch.

**Comment by cucucucumber** [comment]
Hi Jordan, thank you for your instructions. It is my first time participating in such a large project in GitHub, so I'm kinda nervous right now. I must be messed up with the branches when creating the pull request. Per you suggestions, I have closed this pull request and created a new one targeting to the develop branch. Please notify me if any other changes should be made. :)

> The edits you made are not large, so it may be simplest to apply them from scratch on a branch that is built off of `develop`. I wish I could advise you better on using git to find a git way to get it moved, but I'm shaky on some things.

**Comment by cucucucumber** [comment]
> You will probably need to create a new branch, based off of the develop branch. Then you can cherry pick the commit from your forks master branch.

Thank you @drgrice1 I have create a new request targeting the develop branch.

**Comment by taniwallach** [comment]
The issue is being fixed by https://github.com/openwebwork/webwork2/pull/1352.

**Pull request closed without merging**
