### PR TITLE
Obtain an exclusive lock on log files when writing logs

### PR DESCRIPTION
**Pull request by drgrice1**
More is probably needed with this as there are probably other files that multiple server processes could be attempting to write to at the same time.  Finding these would take careful review of the code.

This is to address issue #2016.

### CODE REVIEW

**Comment by drgrice1** [comment]
Note that the Fcntl module used by this is part of the Perl core.  So I don't think it needs to be added to check_modules.

**Comment by pstaabp** [comment]
It seems like the best test for this might be to merge it and for those with a fair number of users to check the log files. I think trying to test on a development machine might have probability near zero to reproduce.

**Comment by somiaj** [comment]
> It would also be good to keep an eye on any performance hits resulting from this, particularly in clustered environments where these log entries could be written to a network location.

I was also wondering if an i/o bottle neck here could cause a active server to slow down as each worker has to wait its turn to write its log.

Would pushing log writing off to minion be a possibility (though this would then make minion mandatory).  Though this might put a layer between the process and logs making debugging issues harder.

**Comment by drgrice1** [comment]
@somiaj:  This certainly won't cause a bottleneck.  It is a quick file open, write a few lines, and close.

**Comment by drgrice1** [comment]
Pushing this off to minion is silly.  This is not a time consuming nor resource intensive task.

**Comment by drgrice1** [comment]
@dlglin:  I doubt this will cause any performance hits.  This is exactly the same code that Mojo::Log uses to handling log writing, and the is certainly designed to fit in with Mojolicous non-blocking behavior.

**Comment by Alex-Jordan** [comment]
My school's production server has many users (55 current live courses), with some instructors even giving quizzes with simultaneous start times. I do not see this issue there (I only looked at the transaction logs, searching for lines that do not begin with `[`. That includes searching transaction logs from past terms and years.)

The same with the Runestone hosting server. And that has twice as many live courses, including one school with an emporium model where hundreds of students are simultaneously active at regular times each week.

So I'm not sure what kind of testing I could do to potentially reproduce the issue.

**Review by Alex-Jordan — APPROVED** [review]
I'm approving this without testing it or closely examining its code. I am thinking that we should just merge it and use what time we have left before the release to keep an eye out for issues. And it is probably good, since @drgrice1 has experience using file locking.

**Review by pstaabp — APPROVED** [review]
Agree with @Alex-Jordan.  Will merge.

**Pull request merged**
