### PR TITLE
Fix keyword searching

### PR DESCRIPTION
**Pull request by jwj61**
Fix bug in library browser where the user enters keywords for their search.  Previously, it was always returning nothing.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Thanks John. Should we also do a hotfix pull request into master? And if so, how does that affect the git flow of the fix? I'm guessing the fix would need to branch from master, and then after merging into master, we merge master into develop?

**Comment by dpvc** [comment]
@Alex-Jordan, you are right, a hot fix should be a branch from master merged into master.  But you don' t pull master into develop (that is not allowed by git-flow).  Instead, you merge the hot fix branch into both master *and* develop.  The merges to master are supposed to be one way (only into master).

**Comment by jwj61** [comment]
So, I should have a single pull request to master?

**Comment by dpvc** [comment]
You should rebase your branch to be off of master and make a pull request to master.  When that is approved, make another pull request to develop to get your patch merged there as well.  You should not have to wait for additional review for the one to develop, once it has been approved for master.

**Comment by dpvc** [comment]
Then I think there needs to be a new tag for 2.13.1 or whatever.

**Comment by mgage** [comment]
Arnie and Alex say this is ok, and it seems right so here goes.

**Comment by Alex-Jordan** [comment]
Mike, you merged this into develop. What do we do with the corresponding #817 into master?

**Pull request merged**
