### PR TITLE
Autouncheck empty date field on the set detail pages

### PR DESCRIPTION
**Pull request by drgrice1**
See the discussion on https://github.com/openwebwork/webwork2/pull/988

Mike, does this fix the issue you described?

### CODE REVIEW

**Comment by mgage** [comment]
Not quite.  Go to set detail 2 for individuals.
Enter dates for closes and answers available.
Delete the date for closes (but don't click anywhere else) -- you get "none specified" and the box is still clicked.
Now press "save changes" -- you will get an error message about a badly formed or missing date
If then reload the page everything will be fine.
Instead of "save changes" you can hit return and get the same behavior.
Thanks for debugging this.

I haven't checked the User detail list page but I expect it is the same.

**Comment by drgrice1** [comment]
Are you sure that you restarted apache2 after checking out this pull request?  I just want to make sure, because for me if I do what you describe with this pull request it works as expected with no errors and the check box is unchecked.

**Comment by mgage** [comment]
Cancel the previous comment.  I hadn't restarted apache2 and flushed all of the css.

**Comment by mgage** [comment]
Everything looks good now.

**Pull request merged**
