### PR TITLE
Increase the required version of Mojolicious to 9.34.

### PR DESCRIPTION
**Pull request by drgrice1**
This version added the encoding option to the `Mojo::File::slurp` method that is used in the `WeBWorK::Utils::Files::readFile` method.

An alternate approach to this pull request would be to not use the optional parameter to the `Mojo::File::slurp` method, and instead do the decoding ourselves.  Then version 9.22 of Mojolicious (the version in the Ubuntu 22.04 repositories) could still be used.

### CODE REVIEW

**Comment by drgrice1** [comment]
By the way, this is the fix for issue #2429.

**Review by Alex-Jordan — APPROVED** [review]

**Review by taniwallach — COMMENTED** [review]
I also got hit by the problem editor having problems with problems with UTF-8 characters (Hebrew) on a local install of 2.19.

Installing Mojolicious from CPAN fixed that for me. I ended up with Mojolicious-9.37, and now the problem editor of 2.19 works properly.

The downside of installing simply from CPAN is that the version installed will be depended on what is the current version of Mojolicious. Hopefully that will not cause different problems in the future.

**Comment by drgrice1** [comment]
If at some point a newer version causes issues, then we will need to document installing a specific version.  You can do this using `cpanm` with `cpanm Mojolicious@9.37`.  However, at this point any version of Mojolicious that is version 9.34 or newer will work.

We also would need to implement a maximum version check in `check_modules.pl`.

**Comment by drgrice1** [comment]
I also updated the docker build to use the latest version of Mojolicious from CPAN in this pull request now.

**Comment by pstaabp** [comment]
Also, requiring newer version of Mojolicious might be beneficial for other features. I don't know any right now, but this could be a reason to go this route instead of #2433.

**Review by pstaabp — APPROVED** [review]

**Pull request merged**
