### PR TITLE
Create fr_CA.po

### PR DESCRIPTION
**Pull request by JonathanDesaulniers**
Added french canadien language file

### CODE REVIEW

**Review by drgrice1 — APPROVED** [review]
Thank you for the contribution.  Note that strings have changed quite a bit since the last release of WeBWorK.  Those strings have not yet been added to the po and pot files.  This will most likely be done about a month or so before the release.  The release is planned to be near the end of March.  Hopefully, you will be able to update the file at that time so the updated translations can be included with the release.

**Comment by drgrice1** [comment]
In case you are interested in getting a start on updating the translations for the new release, I have attached the fr_CA.po file updated with new strings that have been added to the code since the last release.  Of course, there may yet be other strings added before the next release.
[fr_CA.po.txt](https://github.com/openwebwork/webwork2/files/8064258/fr_CA.po.txt)

**Comment by drgrice1** [comment]
I will go ahead and merge this.

**Comment by drgrice1** [comment]
@JonathanDesaulniers : Note that I have added all of the strings that are in the current develop branch to the webwork project in Transifex.  Also, the plan is that in the future all translations will be done there, rather than by making a pull request here.  So if you could go to https://www.transifex.com/webwork and complete the translations for the fr_CA language, that would be great.  Transifex will automatically make a pull request here once 100% of the strings are translated.  At this point, Transifex shows there are 78 strings left to translate.

**Comment by JonathanDesaulniers** [comment]
Excellent, i will try to do it shortly. Thanks


Jonathan Desaulniers
Spécialiste en développement pédagonumérique du RÉCIT
Service national dans le domaine de la Mathématique, de la Science et Technologie
514-668-9656
recitmst.qc.ca

ImageImage
________________________________
De : Glenn Rice ***@***.***>
Envoyé : Tuesday, March 29, 2022 4:25:25 PM
À : openwebwork/webwork2 ***@***.***>
Cc : Jonathan Desaulniers ***@***.***>; Mention ***@***.***>
Objet : Re: [openwebwork/webwork2] Create fr_CA.po (PR #1592)


@JonathanDesaulniers<https://github.com/JonathanDesaulniers> : Note that I have added all of the strings that are in the current develop branch to the webwork project in Transifex. Also, the plan is that in the future all translations will be done there, rather than by making a pull request here. So if you could go to https://www.transifex.com/webwork and complete the translations for the fr_CA language, that would be great. Transifex will automatically make a pull request here once 100% of the strings are translated. At this point, Transifex shows there are 78 strings left to translate.

**Pull request merged**
