### PR TITLE
Make webwork use newer versions of jquery and jquery-ui installed via npm

### PR DESCRIPTION
**Pull request by drgrice1**
This removes all jquery and jquery-ui files from the git repository.  The files are now installed via npm.  Install npm from the Ubuntu repositories, and then run `npm install` from the `webwork2/htdocs` directory.

All of the third-party javascript and css files (those in js/vendor and css/vendor) should be worked into this scheme eventually.  At least as much as possible.

This will not work with the docker installation yet.  Edit:  This is not true anymore.

I am adding this as a pull request to make it more visible.  See https://github.com/openwebwork/webwork2/issues/1015.

### CODE REVIEW

**Comment by pstaabp** [comment]
Trying to test this.  I switched to this branch and ran `npm install` and notice that the new packages are in the `node_modules` directory, but it's unclear that they are getting pulled in. 

Searching through the code, it only appears that the jquery-ui.min.css file is being pulled in--doing a search through all .pm files. 

Anything else that needs to be done or what am I missing?

**Comment by drgrice1** [comment]
After you run `npm install` you should see jquery, jquery-ui-dist, and jquery-ui-themes in the node_modules directory.  These files are loaded in webwork everywhere that they were before.  That doesn't happen much in the perl library, but there are a few places.  Most of these are in the template files.

**Comment by pstaabp** [comment]
I finally got a development machine running. First of all, here's a list of things I checked from the list of changed files that you have.  

- [ ] no pages on basic load seems to have any js errors
- [ ] I checked moving problem order in the homework set editor. no errors
- [ ] I checked achievements and they seem to pop open ok.
- [ ] Checked the library browser and no errors.

Here's some things I see: 

1. In the Classlist Editor, clicking on the pencil icon shows the error:
```
[Error] TypeError: null is not an object (evaluating 'document.getElementById("filter_select").onchange = classlist_add_filter_elements')
	(anonymous function) (jquery.min.js:2:31678)
```
This isn't a jQuery call, but I think it's getting handled by jQuery because being wrapped in a `$()` block to run on load.   This could be an error in the develop branch--I'll try to check this later. 

2. I luckily stumbled on a program that uses DraggableProof and it appears that we need to update that in the openwebwork-problem-library.  This may just need to point to the nestableSortable.js that you updated.    Are there any other problem macros to check?

**Comment by pstaabp** [comment]
Just noticed that issue #516 in the pg repository mentions this.

**Comment by mgage** [comment]
That’s my pull request to attempt to solve the problem.

**Comment by drgrice1** [comment]
The problem with the pencil icon in the classlist editor was not created by this pull request.  You get the same error without this pull request.  Well, almost the same.  The difference is before this pull request the error comes through addOnLoadEvent.js.  Now the error comes through jQuery because I replaced the addOnLoadEvent with jQuery's ready function.

Note that in some cases I replaced the addOnLoadEvent with window.addEventListener("load", ...).  I checked all of those cases and determined which was the correct one to use.  Maybe I should not have used jQuery's ready function at all, and should have used DOMContentLoaded in those cases.  jQuery's ready function is a bit more convenient though as it is guaranteed to run even if the DOMContentLoaded event has already fired.  In any case the addOnLoadEvent.js code is obsolete, and has been since at least when IE 9 was released 9 years ago.

Furthermore, none of these changes have anything to do with the error coming from that pencil icon.  If I get a chance, I will try to fix that.

**Comment by drgrice1** [comment]
Ahh, so the problem is that the elements that have the ids `filter_select` and `export_select_target` do not exist on the page that is opened when you click on the pencil icon (the user editor page).  I added the fix to this pull request.

**Comment by taniwallach** [comment]
We should probably also fix `macros/CanvasObject.pl` in `pg` which has a line:
```
<script language="javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
```

**Comment by drgrice1** [comment]
@taniwallach:  I don't think that macro was ever fully developed.  It is not used by anything in the OPL or Contrib, and I doubt it is used by anyone.  If someone knows otherwise, let me know, and give me a functional example pg file to test with.  For now, I am going to leave that file alone.

**Comment by pstaabp** [comment]
I'm getting a couple of errors.  Not sure what changed: 
* In any problem view:
```
jQuery.Deferred exception: e.indexOf is not a function. (In 'e.indexOf(" ")', 'e.indexOf' is undefined) (2)
(anonymous function) — jquery.min.js:2:84839
(anonymous function) — problem.js:3
e — jquery.min.js:2:30011
(anonymous function) — jquery.min.js:2:30309
undefined
```
This seems to be from line 3 of problem.js (js/apps/Problem/problem.js) related to the achievements.  I had turned on achievements to test something, but seems to throw the error either way.  

I can't figure out why this error is thrown, though. 

* On the Homework Sets Editor, I'm now getting three `Can't find variable: addOnLoadEvent` errors for
   * `form_checker_hwsets.js`
   * `hwsets_handler.js`
   * `show_hide.js`

They are all of the form:
```
addOnLoadEvent(function (){
	document.getElementById("take_action").onclick = check_form_hmwk_sets;
});
```
perhaps we should change these to 
```
$( window ).load(function() {

});
```
instead.

**Comment by drgrice1** [comment]
This sounds like a case of browser caching.  I recommend that you enable the feature (available in most browsers) of the developer tools to disable the network cache.  Clear your browsers cache and then try again.  The problems you are describing are common things I have seen when the browser is using a mix of not updated javascript from the cache, and new javascript from the pull request.

**Comment by pstaabp** [comment]
That did it and explains why I hadn't seen it before. Thanks.

**Comment by drgrice1** [comment]
That last commit to this pull request shouldn't need any testing.

**Comment by pstaabp** [comment]
I am getting some errors related to flash applets.   Since flash is now dead, we just probably just pull those from the OPL.

**Review by pstaabp — APPROVED** [review]
This is looking pretty solid now.

**Comment by drgrice1** [comment]
Are you trying to load the flash problems?  That will cause errors.  There are also java applet problems in the OPL.  They will also cause errors.  All browsers have now dropped support for flash and java.  We need to remove all of the flash and java support in webwork2 and pg.  Although that is general clean up that we can defer until after the release.  As long as you don't try to load those problems there is no issue.

**Comment by drgrice1** [comment]
Another thing we need to discuss is how far back we want to go with browser support.  At this point, I think the only sane thing to do is to go no further back than IE 11.  Although, if no one is opposed, I would be up for dropping all IE support entirely.  That really opens up doors.

**Comment by drgrice1** [comment]
By the way, if I am not mistaken, MathJax 3 requires at least IE 11.

**Comment by drgrice1** [comment]
Please consider merging this so that we can move forward.

**Comment by taniwallach** [comment]
I had tested this using the version from a while back. It is in use on a semi-public development server already for several days with no complaints from the people using that machine.

I am putting it up on my production servers tonight via a personal branch https://github.com/taniwallach/webwork2/tree/jquery-update_and_PR_1190 .

After it is up and running on the production server, I'll run some quick tests again and do the merge, unless someone asks to wait longer. 

My 2 cents: I think getting this merged is more important than being 100% certain that we did miss some loose ends, as until many people put it into use - we are likely to miss some places (ex. in some OPL problems) where there may be dependencies which remain to be fixed. We will need to handle any such hard-to-find issues as they get reported/discovered.

**Review by taniwallach — APPROVED** [review]
I have tested this on several servers, and have it in use on production servers using a private branch merging this PR and one other on top of develop.
I think we have done the best possible testing for such a large change, and am going to merge this now.

**Comment by Alex-Jordan** [comment]
On the development server I am using, I have noticed that the page loads at first, and there is a noticeable flicker that I attribute to some CSS being applied. For example on the Homework Sets page, the table that lists homework sets is initially a more crude, less styled version, and then some fraction of a second later it is in its final form. Occasionally it takes as long as (I'd estimate) half a second.

Using git bisect, I attribute it to this pull request, which is not surprising given what this one is all about. 

Does anyone else see the flicker? Is there anything we can do about it?

**Comment by drgrice1** [comment]
For me the pages load pretty much the same as they always have.  However, I have always seen what you are seeing on all pages in webwork.

**Comment by Alex-Jordan** [comment]
To see the magnitude of the flicker compared to what I have if I rewind, I made a video: http://spot.pcc.edu/~ajordan/Flicker.mp4

I didn't narrate the video well and I cut out the transition. During the second half, I've rewound to before the jquery changes.

The behavior is consistent if I switch back and forth. That is, it's not faster on the earlier head because something cached stuff from the page load on the later head. (But the older stuff may be cached in the browser.)

I'm not complaining but this was a behavior change I thought worth reporting.

**Comment by drdrew42** [comment]
tagging @apizer for putting this into the release notes -- this is a significant change to the install/upgrade process.

**Pull request merged**
