### PR TITLE
Trim leading and trailing space when passwords are set.

### PR DESCRIPTION
**Pull request by drgrice1**
There is some code clean up that I did while initially thinking I would trim passwords where they were set.  Then I found the quick and simple solution.  Passwords are trimmed when cryptPassword is called.

Do we also want to trim passwords when they are entered to sign in?  That is also not hard to accomplish.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
> Do we also want to trim passwords when they are entered to sign in?

I think yes. There is the scenario of an instructor sending a new password to a student over email, and then the student copy-pastes and accidentally grabs a space.

**Comment by drgrice1** [comment]
Okay, I will add that.

**Comment by pstaabp** [comment]
This looks to me.   I did the following
1. made a new student
2. changed the password to " password"

Logging with either "password" or " password" worked fine. 

Question: we talked about how non-WW authentication handles this.  Just looking at code changes, if you're scrubbing only `cryptPassword`, then it appears we leave the other authentication method alone.  Correct?  

I looked at this for LDAP, which is what we use on our campus.   I don't see that this new change will affect that, which I think it good.

**Comment by drgrice1** [comment]
It looks like you are correct, except in the fail over case when checking the password.  Although I am not certain.  How does the password get set locally for that fail over case?

**Comment by pstaabp** [comment]
Definitely, in the failsafe method.  That is, if say, you can't connect to the authentication server, it falls back on the webwork authentication and I think that's what we want. 

My fear was that if the password on the external authentication has a leading space, and we trim before sending then you can never authenticate, since WW has no control on that.  As I can tell, there is no trimming before going to an external authentication.  Is that correct?

**Comment by drgrice1** [comment]
I think you are right, unless that was already the case due to what @mgage had in Authen.pm.

**Review by taniwallach — APPROVED** [review]
The code looks good.

I was able to change a user's password in both the "Classlist editor" and in "User Settings" to passwords with leading and trailing spaces, and then to log in when the number of leading/trailing spaces was different. (Spaces in the middle of the password remained unchanged). Thus, this seems to work exactly as intended.

**Review by pstaabp — APPROVED** [review]

**Pull request merged**
