### PR TITLE
Fix numerous display and html validation issues on the instructor stats page.

### PR DESCRIPTION
**Pull request by drgrice1**
Generally clean Stats.pm up.  That file was a considerable mess.  Many variables were defined and never used, and generally a lot of code was unneeded.

Note that the borders on the svg image that are now appearing were in the code before, but were not appearing because of an error in the style attribute.  That was fixed, and the styles were also converted to proper svg attributes.

For gateway quizzes, the links to problems now work.  Note that there is no valid link to the actual problem in the gateway quiz.  So instead the Problem.pm editMode is used.  This at least gives the instructor a link that works and shows the problem which is really what is important here.

### CODE REVIEW

**Comment by somiaj** [comment]
Tested this out and noticed the following:

+ The problem links in the graph open a new tab/window, while the problem links elsewhere in the two tables don't open a new tab/window.
+ The student stats page and student student-progress page are the same with different titles. Are two pages needed for this?
+ When opening a gateway quiz problem in an undefined set it always says problem 1. This is just how it works, but I was initially confused that I opened the wrong problem since the problem number didn't match. (Not an issue just something that initially confused me).

**Comment by drgrice1** [comment]
Your first two comments are just the way that it is.  I didn't change those.  I can make the links all open in a new tab/window.  The student stats and student progress pages are the same, and I don't plan to change that.

I will see if I can make the problem number be consistent with the problem number in the gateway quiz.  I am not sure that can be done with the current parameters though.

**Comment by drgrice1** [comment]
@somiaj:  The problem number is now the same on the undefined set problem page as on the stats page.

**Comment by drgrice1** [comment]
Also, now all problems open in a new tab/window.

**Comment by pstaabp** [comment]
looks good to me.  One thing that just jumped out at me--although this is the way it was done before--is that the breadcrumbs end in Statistics / Statistics if you are at level of set or a user.  Would it make sense to end the breadcrumb with either set_id or user_id?  Again, not a big deal though.

**Pull request merged**
