### PR TITLE
Develop multi answer fix

### PR DESCRIPTION
**Pull request by mgage**
This branch fixes reported bugs in which only the first answer of a multiAnswer question was recorded for "sticky answers" and into the pastAnswer log.  It still needs extensive testing.

### CODE REVIEW

**Comment by mgage** [comment]
This is companion pull request to pg PR #302. It addresses bugs that occur in multiAnswer and matrix answer evaluators.  Many of the bugs arose because of the change to using the answer evaluator as the primary the primary object for a given answer —rather than the answer blank. (This helps regularize the increasing number of answer evaluators that use more than one answer blank — e.g. matrices and multiAnswer.  At the moment I don’t know of any answer evaluators that share an answer blank — if that comes up there are mechanisms to deal with it on a case by case basis — but no organized protocol.)

**Comment by mgage** [comment]
bug #3003 regarding preserving matrix answers beyond the first answer is fixed.  You can test on 
Library/WHFreeman/Holt_linear_algebra/Chaps_1-4/3.4.58.pg. (Remember to pull pg PR #302 as well as this one.)

bug #3812 is fixed by this PR and the companion #302 for PG.

bug #3822 is fixed by this PR

**Comment by mgage** [comment]
I believe this PR is ready for extensive checking.  It should be checked on questions that call multiAnswer() and check matrices.  I have attached the set definition file containing the questions I used for checking. You will need to change the extension from .txt to .def before uploading it to your webwork course.
[setmultiAnswer.txt](https://github.com/openwebwork/webwork2/files/1055342/setmultiAnswer.txt)

**Comment by Alex-Jordan** [comment]
What is the time line for a next release? I could do extensive checking, but it might creep into July before I would be finished.

**Comment by mgage** [comment]
I’m hoping to get a release ww2.13 out towards the end of June. I would leave out some of the current pull requests — in particular
the ones involving localization or making the ww3 interface ready for prime time. Those two will take a long time to check.

I would pull multiAnswer fix — it will also take a little time to check — but it fixes a number of bugs that have been outstanding
for two or three years.  (If you have any time to do checking that is what I would recommend.)

I’m going to put together a formal plan for which PR to include in ww2.13 — hopefully it will be ready later today or tomorrow.

If you have orthogonal features that you would like included in ww2.13 that are relevant to PreTeX (MBX) now would be 
a good time to submit them.  If they are sufficiently orthogonal that the testing is not too extreme I will try to include them as well.

Once 2.13 is split off we can work hard on the localization and ww3 projects.  I would like to at least make substantial
progress on those so that we can have a 2.14 release in late August. 

Take care,

Mike

**Comment by Alex-Jordan** [comment]
OK, PreTeXt related PR's should wait until the August merge then. They are a mess on my local branches of pg, webwork2, and mathbook. It will take me the summer to organize, commit, and test. I'll try to prioritize doing some testing here before July.

**Comment by mgage** [comment]
OK.  That sounds like a reasonable plan.  Once I get 2.13 branched off I should be able to help some with PreTeXt organization..

Take care,

Mike

**Comment by mgage** [comment]
Here is a better homework test suite for multianswer questions.  This one includes the files for some of the questions which were modified and stored locally rather than being taken from the OPL.

1. Remove .txt suffix and upload to the templates directory
[setmultiAnswer (1).def.txt](https://github.com/openwebwork/webwork2/files/1056397/setmultiAnswer.1.def.txt)

2. Remove .txt suffix and upload into the templates/local directory
[setmultiAnswer (1).tgz.txt](https://github.com/openwebwork/webwork2/files/1056399/setmultiAnswer.1.tgz.txt)
 
3. I forgot this .pg file.  Remove the .txt suffix and upload it into the templates directory
[setmultiAnswerunorderedAnswer_test.pg.txt](https://github.com/openwebwork/webwork2/files/1056402/setmultiAnswerunorderedAnswer_test.pg.txt)

You can also duplicate the multiAnswer set and test it as a GatewayQuiz.

**Comment by pstaabp** [comment]
Here's some questions/comments

1. I imported your set above there were .  There are a few missing  problems: #13, #17, #18. 
2.  I'm also getting errors on some of these: 3, 4, 10, 11, 12, 19, 

All of the matrix questions have the problem similar to 
```
Error in NAMED_ANS_ARRAY_EXTENSION: the answer group name should be passed in 
%options using answer_group_name=>$answer_group_name
The use of ans_label=>$answer_group_name is deprecated.
Answer blank name: MaTrIx_AnSwEr0001_1_0
```
3. Some of these don't seem to have multi_answer related to them (the matrix problems and 14, 15, 16).  It may be using them underneath, but it's not clear that there is multiple answer to them.   

4.  Overall, the ones that are clearly multi answer seem to be working though.

**Comment by mgage** [comment]
Hi Peter,

Thanks for the quick response.  I’ll go find the missing problem files and post a new package.

For the NAMED_ANS_ARRAY_EXTENSION errors:

Did you load the companion PG pull request (#302)?  They work together.  I suspect that is why you are getting these errors.

Some of the matrix answers are also multiAnswer but some are not.  Both answer evaluators use the same
mechanism to connection answer blanks and answer evaluators so I’m testing both of them in these examples.

(and feel free to check other problems involving matrices or multAnswer that I haven’t included.)

Take care,

Mike

**Comment by pstaabp** [comment]
I thought I was using the pg branch too.  Anyway, no errors now.   I've also tested about 10 other multiAnswer problems from the library and seems to be working.  If you update the missing problems (13, 17, 18) then I'll check those, but this looks good.

**Comment by mgage** [comment]
I've uploaded updated versions of the multiAnswer homework test suite.  All of the question files are either standard entries in the OPL or have been placed in the templates/setmultiAnswer/ directory.
The links for uploading

1. Remove .txt suffix and upload to the templates directory
[setmultiAnswer.tgz.txt](https://github.com/openwebwork/webwork2/files/1081630/setmultiAnswer.tgz.txt)
[setmultiAnswer.def.txt](https://github.com/openwebwork/webwork2/files/1081633/setmultiAnswer.def.txt)
[setmultiAnsQuiz.def.txt](https://github.com/openwebwork/webwork2/files/1081634/setmultiAnsQuiz.def.txt)

**Comment by pstaabp** [comment]
Not seeing any error with any of these problems and have done testing on others.  I will pull this and the PG version in.

**Pull request merged**
