### PR TITLE
2.12 Bugfixes

### PR DESCRIPTION
**Pull request by goehle**
This is a pull of assorted bugfixes for release 2.12.  

-  [x] OPL-update:  I increased the size of various fields (space is cheap) and added a check to make sure that edition is a number.  
  -  To test: Run `OPL-update`.  On Ubuntu 16.04 it should fail pre patch.  It should work post patch on any machine. 
-  [x] Show Me Another Default:  I added a config page field for the Show Me Another Default value.  
  -  To test:  Check that the field for the default value appears. 
- [x] Orientation:  I removed a & from a setOrientation file that was preventing hardcopies from generating. 
  -  To test:  Get the new setOrientation and make a hardcopy. 
-  [x] Course Info Box:  I replaced the text in the course info box with something friendlier.  I also added code so that if the text is the "default" then the box isn't shown to students at all. 
  -  To test:  Make a new course with the new course_info.txt file.  Check the text in the box.  Check that students don't see the box if the text is unchanged.  Check that if you change it then students can see the box. 
-  [x] Grades Message:  I fixed a bug where the "additional grades" message could appear to students. 
  -  To test:  Check that the "additional grades" message appears to instructors and not students. 
- [x] Unarchiving:  I fixed a bug where unarchiving a course did  not create the html_temp directory. 
  -  To test:  Archive, Delete, then Unarchive a course.  Check that the course has a file in `webwork/htdocs/tmp`. 
-  [ ] MySQL:  In Ubuntu 16.04 mysql has a flag set which prevents searches that use ORDER BY on a field that is not also being SELECTed.  I changed some queries in ListingsDB so that they work in 16.04. 
  -  To test:  Make sure that the Library Browser works, including selecting subjects, chapters and sections.  Bonus points for testing on a server that has the mysql flag `ONLY_FULL_GROUP_BY` set. 
- [x] Show Totals Only:  I fixed some issue with the show totals only feature of Gateways.  Before it would show students their problem grades on the Grades page and allow them to check and show correct answers.  Now if totals only is used it only shows their totals on the Grades page and disables check and show correct answers. 
  -  To test:  Choose "Totals Only" or "Totals only after answer date" for a gateway and check that you can see your total grade on the Grades page, the Problem Set Page and the actual gateway page, but that you cant see problem scores or check correct answers or show solutions. 
  -  Also check that the other options for Show Scores (Yes, No, After Due Date) all work as expected.  I.E.  The scores are either hidden or not. 
- [x] Just In Time Individual Set Scoring:  Fixed a bug where the scr csv when scoring an individual homework set was malformed. 
  -  To test:  Grade a just in time set and select the "Record Scores for Single Sets" option.  Before the patch the scr file won't have the correct headings or data. After the patch it should have "STATUS" and "ADJ STATUS" for all problems, with the correct data. 
- [x] Set Maker No JS: Fixed an issue where problems could not be added to just in time sets from the set maker no js browser. 
  -  To test:  Add a problem to a just in time set from the setmakernojs library browser.
- [x] SimplePG:  Removed SimplePGEditor config variables from the course config page since we dont use them in ww2.  Nothing to test,  just mark this off if the change is acceptable.   
- [x]  Changed the navigation bar to be a little cleaner.  (removed a bunch of the dashes)
  -  To test:  Edit a problem and look at the navigation bar and make sure it looks ok.  
- [x] Reduced Scoring: Fixed bug where creating a set didn't set the reduced_scoring_date
  -  To test:  Create a set.  Before the patch the reduced scoring date will be at unix time zero, after the patch it should follow the default config setting. 
- [x]  Drag and Drop: Added ability to drag and reorder problems using phones. 
  -  To test:  Use the problem set detail 2 page on a phone.  You should be able to reorder problems after the patch.  
- [x]  Phone Scroll: Fixed an issue where scrolling on chrome mobile would trigger resize event. 
  -  To test:  On a mobile device using chrome, hide the sidebar and then scroll down a long page.  Before the patch the sidebar will pop back open and after it should stay closed.  
- [x]  Scaffolding:  Made scaffold headings tab selectable and respond to pressing enter. 
   -  To test:  Open a problem which uses the scaffolding macro.  Before the patch you cannot select the headers using tab selection and so you cant open closed tabs without a mouse.  After the patch you should be able to navigate scaffolds without a mouse.

### CODE REVIEW

**Comment by goehle** [comment]
I've finished my testing run.  2.12 can be released when this and the associated pg bug fix pull request are merged.

**Comment by mgage** [comment]
If I don't import any sets but go immediately to a student's classlist editor entry and try to assign them all of the homework sets (there aren't any) -- I get this:

WeBWorK Warnings

WeBWorK has encountered warnings while processing your request. If this occured when viewing a problem, it was likely caused by an error or ambiguity in that problem. Otherwise, it may indicate a problem with the WeBWorK system itself. If you are a student, report these warnings to your professor to have them corrected. If you are a professor, please consult the warning output below for more information.

Warning messages

Use of uninitialized value within @setsToShow in hash element at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/UserDetail.pm line 392.
Request information

Time	Tue May 17 16:13:39 2016
Method	GET
URI	/webwork2/testrelease/instructor/users2/gage2/

**Comment by goehle** [comment]
Fixed

**Comment by mgage** [comment]
Hmm.  I get this using the nojs version of the library browser.  I'm adding problems to a jitar set which was created and initialized but has no problems.


Error messages

Modification of non-creatable array value attempted, subscript -1 at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor.pm line 561.
Call stack

The information below can help locate the source of the problem.

in WeBWorK::ContentGenerator::Instructor::addProblemToSet called at line 272 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/SetMakernojs.pm
in WeBWorK::ContentGenerator::Instructor::SetMakernojs::add_selected called at line 1237 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/SetMakernojs.pm
in WeBWorK::ContentGenerator::Instructor::SetMakernojs::pre_header_initialize called at line 214 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
in WeBWorK::ContentGenerator::go called at line 382 of /opt/webwork/webwork2/lib/WeBWorK.pm

**Comment by mgage** [comment]
If I add one blank problem to that set and repeat the attempt to add from the nojs library browser it succeeds.

**Comment by goehle** [comment]
Fixed

**Comment by mgage** [comment]
Couldn't check the ubuntu 16.04 bug.  Otherwise everything is ok.  Library browser works fine for freeBSD

I'm ready to pull it.

**Comment by goehle** [comment]
Ok, sounds good to me.

**Pull request merged**
