### PR TITLE
Force the set name entry inputs to be left-to-right.

### PR DESCRIPTION
**Pull request by drgrice1**
This makes set name inputs behave better for right-to-left languages.

@taniwallach:  Is this all that is needed?  Or did you want all places that set names are displayed to also be forced to left-to-right?

### CODE REVIEW

**Comment by drgrice1** [comment]
@taniwallach:  I have added a start to displaying set names and file names ltr.  This is just a scratch on the surface though.  There is a lot more to do.

**Comment by drgrice1** [comment]
@taniwallach:  Could you check over what I have done so far to see that I am on the right track with this.

**Comment by drgrice1** [comment]
@taniwallach:  I think this is ready to go now.  I think I got all of the set names 'ltr'ed.  File names will take some more work probably, but this is a good start.  Please check it as soon as you can.

**Comment by drgrice1** [comment]
Note that the set names that appear in the "siblings" part of the site nav are "ltr", but not aligned left.  That can be done, but will take some effort with styling to make it look good.  I will let you decide if that effort is needed, or if it will work this way.

**Comment by drgrice1** [comment]
@pstaabp:  I requested your review for testing English mainly (although you can do what you can with testing Hebrew - probably as good as I can do).  Basically, everything should appear the same for English with or without this pull request.

**Review by pstaabp — APPROVED** [review]
As far as I can tell, this looks good.  I did check with English and set names look right.  I also switched to Hebrew and the set names all look LTR as well.

**Comment by taniwallach** [comment]
@drgrice1 I'm sorry I did not get to this sooner. I took a look at the result of these changes in the WeBWorK-2.17 branch, and it certainly helps a lot with the handling of set names in a Hebrew course. Thanks!

**Comment by pstaabp** [comment]
@taniwallach No worries on not getting to it, but (and I know you will) let us know if there are any changes needed.

**Pull request merged**
