### PR TITLE
Fix spelling typos in Student Orientation problems.

### PR DESCRIPTION
**Pull request by somiaj**

### CODE REVIEW

**Review by drgrice1 — APPROVED** [review]

**Review by Alex-Jordan — APPROVED** [review]
Sorry for all the embarrassing typos here.

Although, "spacebar" versus "space bar" is a style choice. This ngram is interesting too: https://books.google.com/ngrams/graph?content=spacebar%2C+space+bar&year_start=1800&year_end=2022&corpus=en&smoothing=3

**Comment by Alex-Jordan** [comment]
Do we have anything yet that in `develop` versus `main` where there is a real difference? Maybe instead of all these hotfix PRs, we could just do another merge from one into the other.

**Comment by somiaj** [comment]
@Alex-Jordan I was on the fence about modifying spacebar, but left it in the changes in the end. Since these are your problems, I can revert it to your previous style.

**Comment by Alex-Jordan** [comment]
It's fine as "space bar", I am not requesting it to be changed :)

**Comment by somiaj** [comment]
I'll make a hotfix PR for this too, assuming others would agree with that.

**Pull request merged**
