### PR TITLE
Update the font-awesome css/js library to version 5.

### PR DESCRIPTION
**Pull request by drgrice1**
Remove font-awesome version 3 from htdocs/css and from htdocs/js/vendor and add version 5 to the list of things installed via npm.

All icons are upgraded to their version 5 equivalents.  Also the hackery of first adding an image (question_mark.png and edit.gif) and then replacing those images with font-awesome icons via javascript is removed.  The font-awesome icons are inserted directly.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Is there anything I can/should do to test this?

**Comment by drgrice1** [comment]
Make sure all icons show up.  That is it.  I think I found them all, but I may have missed some.  These can easily be fixed as they are found and will no break things.  They just won't look good.

**Comment by Alex-Jordan** [comment]
Do I need to do `npm install` again after this? (And I'm not sure I remember that command syntax correctly.) If so, do I just run it without clearing something first?

**Comment by drgrice1** [comment]
Yes.  Just change to the directory `webwork2/htdocs` and run `npm install`.  No need to clear anything first.

**Comment by Alex-Jordan** [comment]
See #529

**Review by pstaabp — APPROVED** [review]
This looks good.  I think I was able to track down the location of all changes and IMO the new icons are shinier.. :)

**Comment by Alex-Jordan** [comment]
There's a conflict here now. I would address it myself, except I am unsure how you want to alphabetize `@f...` Does that come before or after `c...`?

**Comment by drgrice1** [comment]
The conflict is resolved.  I just let npm deal with constructing the package.json and package-lock.json files.  I alphabetizes and such.  It puts the `@` items first apparently.

**Comment by Alex-Jordan** [comment]
I see icons. However before the change, the randomize and view-it icons are crisp:

Screen Shot 2021-03-21 at 4 27 08 PM

And after the change, they are fuzzy:

Screen Shot 2021-03-21 at 4 27 52 PM

Meanwhile the edit icon looks a bit nicer. If this just is how it is, OK.

**Comment by Alex-Jordan** [comment]
The previous icons were Library Browser. I also see a regression in quality in Set Detail. Before:

Screen Shot 2021-03-21 at 4 32 40 PM

After:

Screen Shot 2021-03-21 at 4 32 16 PM

I have a suspicion that I did something wrong, and I'm seeing some sort of default image files. I did run `npm install` again. And that pencil icon seems to be better. So I'm confused.

**Comment by drgrice1** [comment]
@Alex-Jordan:  Those icons are actually bootstrap icons, and not font-awesome icons.  Previously bootstrap icons and font-awesome icons used the same naming scheme.  As a result the font-awesome css would take over and give you the old font-awesome icons instead.  Bootstrap and font-awesome have a history together (font-awesome was originally made for use with bootstrap), and hence the similarity.

Now font-awesome uses a completely different naming scheme.  So what you are seeing for those icons with the font-awesome update are actually not font-awesome icons at all, but are the old bootstrap icons as intended by the old version of bootstrap.  For me they do not look fuzzy, although they are different.

**Comment by drgrice1** [comment]
I see now.  If you zoom in (I think you were doing this with your screenshot), the icons become fuzzy.  This is because the bootstrap 2.3.2 icons (called glyphicons) are actually only png images, and not svg like font-awesome icons.

**Comment by Alex-Jordan** [comment]
They look fuzzy to me on Firefox at the default zoom level.

Those screen shots are from identical default zoom levels, just refreshing a page after switching to the branch with new icons. You can see the "1" is the same in both pictures. The icons seem to get larger and take more space on their buttons. Except the up-down arrow is noticeably smaller.

I like what I see before the change better than after, but I don't think that should hold anything up. I just wanted to note the differences.

**Comment by drgrice1** [comment]
@Alex-Jordan:  Does that look better?

**Comment by Alex-Jordan** [comment]
That does make it look better (imho) in Set Detail. In Library Browser (the icons from the first pics I posted here) it is still the bootstrap png icons.

I'm going to do a PR roundup now before I move my production server to 2.16. I'll circle back to this one at the end. It's not a big deal if the icons remain bootstrap.

**Comment by drgrice1** [comment]
Right.  I forgot about those.  I will work on that.

**Comment by drgrice1** [comment]
Okay.  Set maker icons are updated.  These icons really do look better!

**Comment by drgrice1** [comment]
Uh, I meant to delete the TEXINPUTS stuff from webwork.apache2.4-config.dist.  That won't work anymore.

**Comment by drgrice1** [comment]
Oops.  Wrong pull request.

**Comment by Alex-Jordan** [comment]
Can you rebase this or otherwise resolve the conflict? I will test this one last time and merge next.

**Comment by drgrice1** [comment]
@Alex-Jordan:  I fixed the merge conflicts.

**Comment by taniwallach** [comment]
I have not been following this thread much.
I take it that after this was merged - we can close https://github.com/openwebwork/webwork2/issues/529 .

**Comment by Alex-Jordan** [comment]
I think I found another one: the download hardcopy icon that only students see.

**Comment by Alex-Jordan** [comment]
> I think I found another one: the download hardcopy icon that only students see.

From what I can tell, the only font-awesome download icon variant that is free is the solid `fas` one. The `far`, `fad`, and `fal` ones won't load for me and I think it is because they are not free. But I can't find out how to confirm.

The `fas` one is very bold/dark. Ia am working in this vicinity with the GW quiz reordering PR (#1282). Should I go ahead and cahnge it to the solid font-awesome icon?

Instructors rarely see this one, and students see it pretty much all the time.

**Comment by drgrice1** [comment]
Mostly only the fas ones are available, but quite a few of the far ones are as well.  The rest don't work.  If you go to https://fontawesome.com/icons and search there, the ones that aren't grayed out are available.

**Comment by drgrice1** [comment]
What is this download hardcopy icon that you are talking about?  I can't find it even if I am signed in as a student.

**Comment by drgrice1** [comment]
I see it now.  I wasn't looking hard.  It is on the main page.  How about `<i class="far fa-arrow-alt-circle-down"></i>`.  That seems to be the closest to what we have now.

**Comment by Alex-Jordan** [comment]
OK, I will fold that into the #1282. Part of that has lots of code cleanup with indentation, and I think there would be a conflict if I don't put it there.

**Pull request merged**
