### PR TITLE
add German language file

### PR DESCRIPTION
**Pull request by fabiangabel**
derived from es.po

### CODE REVIEW

**Comment by drgrice1** [comment]
@fabiangabel:  It looks like you are using a de.po file created from the webwork.pot file that is currently in the develop branch.  I recommend that instead of doing that, you run the `update_localization_files` script with your current de.po file.  This will update the file for all of the strings currently in the code.  If you don't do this, then you will end up wasting a lot of effort now for strings that have changed, and you will also be missing many strings that have been added.  We need to update the pot and po files in the develop branch, and will probably do that this week, but in the mean time you can already use that.  Note that running the `update_localization_files` will also tell you about errors in your translation file.  There are a few that you will need to fix.  The file won't update with the script until you fix those errors.

**Comment by fabiangabel** [comment]
@drgrice1 thank you for pointing out `update_localization_files` script, I just fixed the errors and will push the new version of the po file now. It seems like the "deprecated strings" appear in the last section of the .po-file?

**Comment by fabiangabel** [comment]
@drgrice1 Thanks for adding me to the transifex team. I have also uploaded the current translation there. What is the recommended workflow? I would have assumed to work locally and keep updating the transifex entries via upload?

**Comment by drgrice1** [comment]
@fabiangabel:  The plan is that all translations will be done in Transifex from now on.  You can either download the file from there, edit it, and upload it again.  You can also edit the strings directly via the Transifex web interface.  Once pull request #1632 is merged this will become the official way to do translations.  After that, as soon as any language is 100% translated, Transifex will automatically make a pull request here with the updated translation strings.  We can also manually trigger the generation of pull requests at lower percentages if needed.

**Comment by fabiangabel** [comment]
@drgrice1 Alright, I think that most of the student interface (excluding the Achievements) is translated now (45% according to Transifex).

> Once pull request https://github.com/openwebwork/webwork2/pull/1632 is merged this will become the official way to do translations.

Should we close/merge this PR then? Reaching 100% of the translation seems to be out of reach at the moment.

**Comment by drgrice1** [comment]
It would be best to leave this pull request open for now to keep this in mind.  Don't worry about reaching 100%.  As I mentioned, we can also manually trigger a pull request from Transifex.  The plan is to do that at release time, even if a translation is not 100% translated.

**Pull request merged**
