### PR TITLE
aaaa

### PR DESCRIPTION
**Pull request by JackZhou303**

### CODE REVIEW

**Comment by mgage** [comment]
Dear Jack Zhou.  

Thanks very much for your contribution and the work you have done on achievements and gateways. It will take a while to review it.  One thing that would help a great deal is if you could resubmit this pull request to the develop branch of webwork2 instead of to the master branch of webwork2.  Ideally you will have made your changes on top of a fresh pull of the develop branch.  
This will mean that we can pull the new work without repulling older commits and thereby muddying the trail of commits and when they were made.  

Thanks.  It's midterms week this week but we'll try to take  a closer look at this pull request over the weekend once we have everything graded. 

Thanks again.

Take care,

Mike

**Comment by mgage** [comment]
I was able to change the target of the pull request do develop from this end.  (It's a newish feature of the github site and this is the first time I've used it.  It's neat.  )    This cuts down the apparent size of your pull request and will make it easier to check.  Thanks again for your contribution.

**Comment by Alex-Jordan** [comment]
I'm confused about what is happening here. It almost feels like an accidental pull request that was intended for a different fork.  It appears that 8 separate GitHub users have contributed to the DuquesneCOSC445W fork with about 20 commits, and those are now packaged together in this one pull request. 

Starting this summer, I'll begin helping evaluate pull requests, but if they come bundled together like this without more explanation of what the intent of each commit (or related commits) is, it will be too hard for me to analyze.

Also, if there are this many active WeBWorK developers, that's great!

**Comment by mgage** [comment]
I'm suspecting a class at Duquesne University is working on webwork -- which is fantastic.  If one the contributors is reading the issues posted here it would be helpful if you could contribute a few lines about the goal the class has in mind.  My schedule is jammed this weekend but I'll try to track things down next week.  A an outline of what is being attempted will help.

**Comment by drjeffjackson** [comment]
Sorry for the confusion.  One of my students generated this pull request and should not have.  Please reject it.

**Comment by mgage** [comment]
This pull request is not yet ready to be pulled.  It's a work in progress by the class COSC445W at Duquesne University taught by Prof. Jeffrey Jackson.  They are working on providing  a GUI to simplify the creation and editing of certain standard types of problems.

**Pull request closed without merging**
