### PR TITLE
Remove PGML from ASimpleCombinedHeaderFile.pg.

### PR DESCRIPTION
**Pull request by drgrice1**
This was added in PR #1058 and breaks hardcopy generation.

### CODE REVIEW

**Review by taniwallach — APPROVED** [review]
There was really no real need to PGML in the header file, and we had flagged the issue as a problem before. This changes things back to avoid the problem.

I think this minor correction should be merged ASAP.

**Comment by taniwallach** [comment]
Mike opened an issue requesting a fix in https://github.com/openwebwork/webwork2/issues/1066. If someone eventually fixes the issue, we can then try PGML again in the header file.

@drgrice1 - @mgage  is apparently very busy with other things. I think we can merge without his review of such a minor change.

**Comment by drgrice1** [comment]
I agree.  You can go ahead and merge it.  It has become cumbersome to continue to need to change the set hardcopy header file every time you are testing things with new sets on the develop branch.

**Comment by mgage** [comment]
Go ahead and merge it.  I was hoping we could fix the hardcopy issue quickly.  I often use the header to list topics describing the homework set and the problems and the PGML markdown lists are very convenient.

**Pull request merged**
