### PR TITLE
move primary coloring in navbar to student-accessible menu items

### PR DESCRIPTION
**Pull request by Alex-Jordan**
This changes the navbar coloring so the student-accessible menu items get the primary coloring instead of the others below.

Also the "MAIN MENU" h2 gets coloring with the primary color. That h2 had `opacity: 0.6` and it looked a bit too light to me, so I changed it to 0.7. (I also tried removing the opacity setting so it was as dark as the main banner and active item, but that looked bad.)

Note that if this is a good way to go, then #2008 should be closed unmerged.

Here are some screenshots. One of them has a set and problem number opened so you can confirm the coloring applies to nested things in the nav tree. "Achievements" is gray in one of them because the mouse was hovering over it when I took the screen shot.

Screen Shot 2023-05-30 at 11 50 25 AM

Screen Shot 2023-05-30 at 11 50 03 AM

Screen Shot 2023-05-30 at 11 49 23 AM

Screen Shot 2023-05-30 at 11 51 44 AM

### CODE REVIEW

**Comment by pstaabp** [comment]
Related question: Another thing that I've been playing with is that the links on the breadcrumbs for some of the themes are hard to tell apart from the end of breadcrumb (which is not a link)  I'm using a variation on the green theme that @Alex-Jordan posted above.  Is there a more general way we could handle this? Or tweak on the theme basis?

**Comment by drgrice1** [comment]
I am seeing a contrast issue with the "MAIN MENU" text on all themes except "math4-yellow".

**Comment by Alex-Jordan** [comment]
@pstaabp I put the `link-primary` class on the anchors, and at least in the blue theme, it makes a small difference. Not sure it's enough to get at what you are after though. I think to do that, you might need to wrap the last one in a span and put some class on that span.

**Comment by Alex-Jordan** [comment]
> I am seeing a contrast issue with the "MAIN MENU" text on all themes except "math4-yellow".

You see it locally, or in my screenshots?

**Comment by drgrice1** [comment]
I think that with the background color being the primary color, you should completely remove the opacity.  That looks much better to me, and solves the contrast issue.

**Comment by Alex-Jordan** [comment]
I can do that. But it looked off to me to have the background color be fully opaque and therefore match the "MAA" background, with the WW logo background a lighter version. The effect was that instead of three rectangles, it was one rectangle (the WW logo) and then a jagged octogon. The dividing border line didn't totally kill that illusion for me. Do you see any of that when looking with the opacity removed?

**Comment by drgrice1** [comment]
I did see that.

**Comment by Alex-Jordan** [comment]
I removed the opacity. Now for example in green:

Screen Shot 2023-05-30 at 2 01 11 PM

I( tried moving it to 0.8 first, which fixed the contrast issue for blue, but not green.)

**Review by drgrice1 — APPROVED** [review]
This looks good.

It would be nice to figure out a better way to make the header and "Main Menu" more differentiated.  But @Alex-Jordan will probably figure something out at some point.

**Comment by somiaj** [comment]
Now that this is on my live server, I do notice the following looks a bit odd. I remove the 'Courses' link from my menu as once a student is in a course, they don't really need to get out to a list of all courses.  This does make it so the menu header and selected item have the same color.

ww-menu

**Comment by somiaj** [comment]
Note, I can edit my themes CSS to get things to look nicer here, just sharing the result.

**Pull request merged**
