### PR TITLE
Ww2gb

### PR DESCRIPTION
**Pull request by aorinevo**
* GradeBook MR

### CODE REVIEW

**Comment by aorinevo** [comment]
@pstaabp and @mgage here is the initial MR for the GradeBook that CUNY is using.

**Comment by mgage** [comment]
Hi Aori,
Finally getting to this.  

There are a few startup issues.  

1.There are some <<<< ..  ==== >>>> lines
in ContentGenerator.pm left over from a merge that wasn't completely resolved.

2. There is some raw JSON code displaying in the CourseConfig Page:



3. The help in the question marks on this page are good enough stubs for me, 
but they will need more work for a release. 

4. When I visit GradeBook page (now visible) I see:

```
node instructor_statistics_old doesn't exist in node list: failed at /Volumes/WW_test/opt/webwork/webwork2/lib/WeBWorK/URLPath.pm line 1255.
Call stack

The information below can help locate the source of the problem.

in WeBWorK::URLPath::visitPathTypeNode called at line 1317 of /Volumes/WW_test/opt/webwork/webwork2/lib/WeBWorK/URLPath.pm
in WeBWorK::URLPath::visitPathTypeNode called at line 1317 of /Volumes/WW_test/opt/webwork/webwork2/lib/WeBWorK/URLPath.pm
in WeBWorK::URLPath::visitPathTypeNode called at line 1317 of /Volumes/WW_test/opt/webwork/webwork2/lib/WeBWorK/URLPath.pm
in WeBWorK::URLPath::visitPathTypeNode called at line 1164 of /Volumes/WW_test/opt/webwork/webwork2/lib/WeBWorK/URLPath.pm
in WeBWorK::URLPath::getPathType called at line 902 of /Volumes/WW_test/opt/webwork/webwork2/lib/WeBWorK/URLPath.pm
in WeBWorK::URLPath::newFromPath called at line 145 of /Volumes/WW_test/opt/webwork/webwork2/lib/WeBWorK.pm
```

5. It seems likely that most of these are surface glitches caused because you have been working with both ww3 and ww2.  My ww3 files are somewhat out of date in this branch, but I was assuming that they wouldn't be needed.  I'm using a fresh pull from openwebwork, develop branch and then a pull from your branch ww2gb.  I didn't make any changes in the pg software, I'm using openwebwork develop branch for pg. 

6. Chances are you can see what is wrong quickly ( certainly the first bug is easy to fix).  If you patch them in your ww2gb branch and push it to aorinevo:ww2gb, your branch on github then the changes will automatically appear here.  You won't have to resubmit the pull request.  

7. Looking forward to getting this working.

-- Mike

**Comment by aorinevo** [comment]
Hi Michael, fixed the errors and tested locally.  Now the page should render without errors.

**Comment by mgage** [comment]
Hi Aori,
Thanks for the updates.  It compiles now. I am still seeing JSON on the CourseConfiguration page as in the previous screen shot and I cannot set any Gradebook Configurations.  I have set both "Gradebook on Grades page" and "enable gradebook for instructors" to true, saved the page and I cannot find any link to the Gradebook page. (in the last round I could find such a link but it gave me a "node" error (see 4 above). Now I cannot find the link at all.

It would help me if you could write a short paragraph with the next submission of a couple of steps I should take to make sure that gradebook is visible and perhaps one or two things to check in viewing the gradebook (that you are sure that will work) -- that will help me get familiar with how the feature is supposed to work. I can poke around on my own from there.   Thanks much.

-- Mike

**Comment by aorinevo** [comment]
Hi Michael, The JSON on the configuration page is expected.  

After you save the options you need to refresh the page, or navigate away.  Then the link shows on the left.
screen shot 2017-01-29 at 7 35 57 pm

Hopefully this works.

**Comment by mgage** [comment]
Hi Aori,

OK.  I have it working now.  For some reason I got or created a bad copy of ContentGenerator.pm and successive pulls were not updating it.  I started over again and things seem to be working.

I finally figured out that I needed to assign new types to each homework set from the homework set editor. I think it would be useful to use homework, gateway/quiz,  proctored gateway/quiz, and just-in-time as labels (plus the new labels) so that earlier courses and homework don't have to be relabeled.   (e.g. HW -> homework and quiz -> gateway/quiz)  Out of curiosity what is OCEs? 

I figured out what the JSON is doing in CourseConfiguration and it's fine for now although we need to figure out a way to present and/or explain it to new users of the gradebook. 

The menu feature on the gradebook page is neat and quite useful since I'm testing this on a demo class with several hundred students and 50 assignments (not all of them assigned). 

I couldn't immediately figure out the purpose of the "Gradebook on Grades" switch.  I didn't see any noticeable difference on the grades page.

I'll keep poking around.  Looks good so far.

-- Mike

**Comment by aorinevo** [comment]
I removed gateway/quiz and proctored gateway/quiz, because these are versioned.  I didn't have time to complete this part.  

I forgot what OCE stands for but Annie probably remembers.

**Comment by mgage** [comment]
Got it.  I’d still like to change HW to homework so that it is backward compatible (or if necessary 
have the menu item accept them both  as synonyms — although that is a little messy).

I’m not 100% sure why I can’t filter for homework sets right out of the box on an old 
course.  Is it that the filter is searching for the wrong token (e.g. HW instead of homework?) or does each old homework assignment have  to be edited in order to update some field so that the filter can work?

Still looking very good.  Nice work.

— Mike

**Comment by aorinevo** [comment]
That's right; an old homework assignment would need to be edited and changed to HW to be filterable in the gradebook as an HW.

**Comment by mgage** [comment]
OK.  I think we can pull this to develop if we take care of some of the relatively things.  There are some hard things that need to be addressed eventually but they can be handled in subsequent pull requests.

1. Make modifications so that the gradebook works automatically with existing homework  sets and gateway/quiz sets. It doesn't need to grade gateway/quiz sets, it can fail gracefully somehow,  perhaps with a note that no grade is available.  Currently it destroys gateway/quiz sets and it is impossible to reset the status to gateway/quiz. 
 
2. Add an explanation (to the question mark pop-up) of what the "Gradebook on Grades page" actually does. 
         * P.S. -- what _does_ it do? :-) Is there a more descriptive name?

3. Add an explanation to the question mark pop-up for enabling the gradebook that describes what the JSON data in the configuration window does (and how to modify it properly). That will work for now.

4. Add an explanation somewhere (starting with these PR comments) of how the new homework types quiz, final, midterm, labs, class participation, test, quiz, exam, discussion, OCEs, are to be used.  How do you enter grades for a test or class participation .....    

For the long term (future improvements to the gradebook feature)

1. Find a better mechanism for configuring the gradebook that doesn't depend on getting the JSON syntax exactly right.

2. Decide whether in the long run we want to be able to enable and disable the gradebook from the CourseConfiguration page? or should this be handled in the localOverrides.conf file in the same 
place that the other editors  -- (classlist editor, homework editor, etc.) are handled. 

3. Figure out how to report gateway/quiz grades which are versioned. 

4. Figure out efficient ways to enter a large number of grades for things like quizzes and exams. Probably some javaScript on the Gradebook page could push data into the appropriate row of  the 'homework set' datatable.

**Comment by drgrice1** [comment]
This has been here long enough, and clearly is not going to be merged.  It will still be listed in the closed pull requests for historical purposes.

**Pull request closed without merging**
