### PR TITLE
Change the serialization/deserialization code for the last_answer database field

### PR DESCRIPTION
**Pull request by taniwallach**
Motivation is to address the issue discussed at: 
  - https://github.com/openwebwork/webwork2/issues/1031
  - http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4662#p13763

Change the serialization/deserialization code of `encodeAnswers()` and `decodeAnswers()` of `lib/WeBWorK/Utils.pm` which are used to encode/decode the last_answer field in the COURSEID_problem_user table to use JSON instead of `Storable::nfreeze()` and `Storable::thaw()` which failed to properly handle UTF-8 data in answers, or many answers with over 127 characters (due to the binary length code appearing to be an invalid UTF-8 character).

The `decodeAnswers()` falls back to the **old** `Storable::thaw()` based code for backwards compatibility when the value returned from the database does not seem to be a JSON array (currently detected by checking for a leading `[` and a trailing `]`) while the `Storable::nfreeze()` data seems to always start with several control characters.

The new code has been tested with homework problems, and stores long answer strings, answer strings with UTF-8 characters, and prior last_answer data from the old format seems to load properly in all cases tested.

Testing was **not** done with gateway problems.

### CODE REVIEW

**Comment by taniwallach** [comment]
@drdrew42  - It would be good if someone tested the change with MathQuill enabled. Could you possible test it?

**Comment by drgrice1** [comment]
I have tested this with MathQuill enabled.  In particular I tested this with the problem that Sean posted on the forums that led us to this issue.  It works fine.

**Comment by mgage** [comment]
it worked for me in a fresh download of webwork-2.15 in a docker container

**Comment by sean-fitzpatrick** [comment]
Thanks everyone for your prompt attention on this. I will go update my local WeBWorK install right now, and then re-enable MathQuill. If anything doesn't work, releasing 280 calculus students on it should find it. Do I need to upgrade databases after doing a git pull?

**Comment by mgage** [comment]
I think you can get by without doing a database update.  It's been pointed out that with the change to webwork-2.15 the upgrade course procedure does not completely update things.  It adds new fields and tables as necessary but if the size of a field has changed it doesn't notice.  Potentially this could cause problems but so far it's not clear if it will.   That should be a project for the next release however --- to review how the database is managed from the admin webpage and anticipate any problems.

**Pull request merged**
