### PR TITLE
Rename Hwmk Sets Editor and Classlist Editor

### PR DESCRIPTION
**Pull request by drgrice1**
This changes the names in the site nav as discussed in https://github.com/openwebwork/webwork2/issues/1992.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Do we want to have "Assignment Manager" but right above it we have "Set Assigner"? What I mean is, referring to a set as an "Assignment" in one place, and as a "Set" right next to it.

**Comment by somiaj** [comment]
We also have 'Homework sets', and 'sets' gets used to refer to. Maybe just call it 'Set Manager' to be consistent with what they are referred to elsewhere. Advantage of this is a shorter name.

**Comment by drgrice1** [comment]
@Alex-Jordan: Yeah, that is a good question.  I have had this branch sitting here for a while (since shortly after @dlglin made that issue), and decided to put it out there to further the discussion.

I like "Set Manager".  I will wait for a bit before making the change to see what others have to say.

**Comment by drgrice1** [comment]
I went ahead and made the change from "Assignment Manager" to "Set Manager".

**Review by somiaj — APPROVED** [review]
Lke the Chnge

**Comment by pstaabp** [comment]
Also, just searching "Hmwk" there are a number of translations (in webwork2.pot) that include this.  Do we need to update this, or is it sufficient to wait until release time which will then update. 

Lastly, there are a couple of comments in defaults.config with "hmwk" that should probably be updated as well.

**Comment by drgrice1** [comment]
I fixed the things you noticed.  Thanks for pointing those out.

The `po` files should not be modified directly.  At some point we will run the `bin/dev_scripts/update-localization-files` script, and commit the changes it makes.  It will take care of those things.

**Review by pstaabp — APPROVED** [review]

**Review by drdrew42 — APPROVED** [review]
👍 -- although the branch name had me banging my head 💀

**Comment by Alex-Jordan** [comment]
Three approvals, plus I presume Glenn's.

**Pull request merged**
