### PR TITLE
WeBWorK 2.13 client dir cleanup

### PR DESCRIPTION
**Pull request by mgage**
Cleaned up the client directory removing obsolete scripts.  

Rewrote README describing  the new script for rendering PG questions outside the WeBWorK2 frame work: `sendXMLRPC.pl`

Removed obsolete files from webwork2/conf

Removed obsolete directory RPQ

Added file lib/FormatRenderedProblem.pm which seemed to be missing from the develop distribution?

### CODE REVIEW

**Comment by mgage** [comment]
A version of this pull request should be submitted to develop as well once this one has been checked out.

**Comment by pstaabp** [comment]
Are there any specifics to testing this branch?

**Comment by mgage** [comment]
For testing the reorganization of the clients branch:    Follow the directions in the README and see if you can render a library problem from the command line.  This should work out of the box rendering on the computer at hosted2.webwork.rochester.edu

Set up a local credentials file and render a problem by sending the rendering request to a computer on your site. 

Correct or clarify the instructions in the readme if necessary.

You don't have to try all of the switches -- this file has been around for a while and used often. The purpose here is to make this ability to render problems from the command line visible to a wider audience.  It's the instructions in README that need to be vetted.

There is an outside possibility that I've hidden a the script for a previous version of this capability inside the `old` directory.  I _think_ that sendXMLRPC.pl has all of the functionality of the previous incarnations and I've hidden the old versions to avoid confusion, but if there is a script in `old` that you have found a use for that is not met by sendXMLRPC.pl sound the alarm.

**Comment by mgage** [comment]
This is a stale version of sendXMLRPC.pl that doesn't contain the ability to TeX pg problems.  I'm going to close this temporarily and update it.

**Comment by pstaabp** [comment]
I was having some other problems with this as well.  

* even though I didn't have the --crendentials flag on, it was still reading it. 
* the README.md and help for the credentials doesn't have quite the right format.  For example `FORM_ACTION_URL` has a $ in front in the README.md.

**Comment by mgage** [comment]
Hi Peter,

I’m withdrawing this for now.  It’s looking like I made updates in two different branches and didn’t get around to reconciling them
before I got dragged on to the next project.  I’ll delay submitting this feature until 2.14.  It’s frustrating but it should only 
take me a few hours once I get back next week to figure this out and test it again.  And it should be much improved for the
extra effort :-). 

Take care,

Mike

> On Jul 17, 2017, at 12:02 PM, Peter Staab <notifications@github.com> wrote:
> 
> I was having some other problems with this as well.
> 
> even though I didn't have the --crendentials flag on, it was still reading it.  — I think that’s a feature — this is to specify a specific credential file instead of the defaults — but 

> the README.md and help for the credentials doesn't have quite the right format. For example FORM_ACTION_URL has a $ in front in the README.md.
               yeah — that’s one of the changes that got made differently in the different branches.

**Pull request closed without merging**
