### PR TITLE
Replace the jquery-ui-timepicker-addon with flatpickr.

### PR DESCRIPTION
**Pull request by drgrice1**
The flatpickr library was chosen because it is somewhat similar to the jquery-ui-timepicker-addon that we were using, and its usage is simple.  Instead of sliders for hours and minutes it uses numerical inputs.

Also it is an actively maintained library.  Its homepage is https://flatpickr.js.org/ and its source located at https://github.com/flatpickr/flatpickr.

I chose the dark theme that it provides, but there are other themes that could be chosen.

Note that the library also provides localization support, although this pull request does not implement that.

Make sure to run `npm install` in `htdocs` to install the flatpickr package to test this.

### CODE REVIEW

**Comment by pstaabp** [comment]
Overall, I think it looks good.  I think the light theme may go better with the rest of the UI.

**Review by pstaabp — APPROVED** [review]
Looks good.  Also, just tested on a phone and the picker looks a bit different but easier to use with fingers.

**Comment by drgrice1** [comment]
Yes, this is definitely easier to use on touch screens than the jquery-ui datetime picker was.

**Comment by drgrice1** [comment]
Darn, I forgot that the knowl rewrite makes the javscript `defer`ed so that it will also work with webwork3.  So there will still need to be a paired webwork2 pull request.

**Review by drdrew42 — APPROVED** [review]
This looks great -- good riddance to time sliders.

**Pull request merged**
