### PR TITLE
WeBWorK 2.18

### PR DESCRIPTION
**Pull request by drgrice1**
This is the release candidate.  Pull requests that are desired to be in the release should be target on this branch.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
If I'd like for somebody else's PR to be targeted to this branch, should I just move the target myself? Or ask that person?

**Comment by drgrice1** [comment]
You can move it.

**Comment by Alex-Jordan** [comment]
At what point do we change the VERSION file to say 2.18?

**Comment by drgrice1** [comment]
We just have to merge #1947 for that.  We can do that anytime now.  I have been holding off as it makes it easier to keep develop and the release candidate branches in sync.  I think it is time now though.

**Pull request merged**
