### PR TITLE
Update date and version in webwork2.sty

### PR DESCRIPTION
**Pull request by dlglin**
I'm assuming that we want to keep the version of webwork2.sty in sync with the version of WW.

I guess that this (and pg.sty in the pg repo) should probably be added to the release checklist.  Does such a thing exist?

### CODE REVIEW

**Review by somiaj — DISMISSED** [review]
Toomany places to update this version string....

**Comment by Alex-Jordan** [comment]
I think this would be unnecessary if not for the bug about old LaTeX versions being fixed now. In other words, if nothing were changing in this sty file, I don't think we need to feel like updating this version number. I could have (should have?) just called it version 1 when it was born. And then version 2 would be the version with the recent change.

This needs a parallel PR into develop.

**Review by Alex-Jordan — DISMISSED** [review]

**Review by drgrice1 — DISMISSED** [review]
This is ready to merge, but does need a corresponding develop PR.  Do you want me to create that for you @dlglin?

**Comment by dlglin** [comment]
> This is ready to merge, but does need a corresponding develop PR. Do you want me to create that for you @dlglin?

Yes, that would be appreciated.

**Comment by somiaj** [comment]
I'll create one for that.

**Comment by somiaj** [comment]
I just noticed the author has a local email address, should this be changed or is this really @dlglin email address?

```
Author: Danny Glin <dlglin@Dannys-MacBook-Pro.local>
```

**Comment by drgrice1** [comment]
I created a pull request to develop.

The email should be updated for future pull requests!

**Review by drgrice1 — APPROVED** [review]

**Review by Alex-Jordan — APPROVED** [review]

**Pull request merged**
