### PR TITLE
Update setOrientation

### PR DESCRIPTION
**Pull request by apizer**
Update setOrientation to be compatible with the current version of WeBWorK.

### CODE REVIEW

**Comment by goehle** [comment]
This pull is to develop.  If you want it in release 2.11 you will need to close this pull request, rebase over to release-2.11 and make a new pull. 

Geoff.

**Comment by apizer** [comment]
OK,

I thought it would be easier to send it to develop but it should go in
2.11.  Is there an easy way to do this that you can tell me in a few
words?  Otherwise I'll copy the 7 changed files to some non git directory
and copy them back after I checkout 2.11

Arnie

On Wed, Sep 9, 2015 at 3:54 PM, Geoff Goehle <notifications@github.com>
wrote:

> This pull is to develop. If you want it in release 2.11 you will need to
> close this pull request, rebase over to release-2.11 and make a new pull.
>
> Geoff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_openwebwork_webwork2_pull_632-23issuecomment-2D139027632&d=BQMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=5ziiSJ3DOoTGqPl6nDxUAfldhiKwv6gUXIwGkofE3Yo&m=V47gC5sPoctgpmGdkP1rdPTyR5I6hYfvxar17ZwweEE&s=9xWBiiDmay1G4XIRaZdxQ0M5m7n2eL33QcK8jSi4H14&e=>
> .
>



-- 
Prof. Arnold K. Pizer
Dept. of Mathematics
University of Rochester
Rochester, NY 14627
(585) 766-8812

**Comment by goehle** [comment]
In theory the command to rebase this should be 
```
git rebase --onto release-2.11 develop update_orientation
```

**Comment by mgage** [comment]
Arnie,

There have been a couple of complaints about the Union College specific directions on a couple of pages
(referring to the maroon margin or something like that).  As long as you are redoing this why don’t you
read through and take them out.

My own view is students and their profs are being overly picky — but it’s not really worth fighting. :-)


Take care,

Mike

**Comment by apizer** [comment]
Hi Mike,

All that stuff is taken care of.

Arnie

**Comment by mgage** [comment]
Great.  Thanks.

**Pull request closed without merging**
