### PR TITLE
WeBWorK-2.13

### PR DESCRIPTION
**Pull request by mgage**
Candidate for release 2.13 of WeBWorK.  There is a companion 2.13 version of PG as well.

### CODE REVIEW

**Comment by pstaabp** [comment]
Anything in particular that should be tested for this?  I figure try many of the changes... Do we have a list for this?

**Comment by mgage** [comment]
I'll start compiling a list of changes and new features after lunch.  I'll post it as an "issue" for now and we can move it to release notes on the main WeBWorK wiki later. 

One check that could be done now is to make sure that I captured all of the configuration changes into the *.dist  files by using the .dist files to create the site.conf, and localOverrides.conf and webwork.apache-*  files from scratch.

**Comment by dlglin** [comment]
Just got this up and running.  First issue:
2.13 requires Data::Dump, which is not listed in check_modules.  Is this different enough from Data::Dumper that both are necessary?

**Comment by pstaabp** [comment]
This has come up before.  I've been using `Data::Dump` because I like the format for debugging better.  I would vote for adding it to the `check_modules.pl`, but if other feel it is unnecessary, then I can make sure that it is scrubbed before submitting.

**Comment by mgage** [comment]
Probably not but Peter Staab has found it a useful upgrade and uses it with webwork3.

I’ll add it to the check_modules.pl.  I think it’s not hard to add.  

I see Peter has replied as well.

Take care,

Mike

**Comment by dlglin** [comment]
The Rserve stuff works for me.
I added a (commented out) section to localOverrides.conf with the appropriate command to enable Rserve.  I accidentally committed it directly to this branch, rather than as a PR.

**Comment by mgage** [comment]
That's fine.  I've pushed a couple of configuration changes directly as well

Thanks

Any thing substantial should be a pull request for transparency but a direct commit still makes it clear what changed


Take care,

Mike

On Jul 11, 2017 6:46 PM, Danny Glin <notifications@github.com> wrote:

The Rserve stuff works for me.
I added a (commented out) section to localOverrides.conf with the appropriate command to enable Rserve. I accidentally committed it directly to this branch, rather than as a PR.

**Comment by pstaabp** [comment]
Mike, did you get a chance to get some documentation/release notes together?  I've been holding off other testing until I look at those.

**Comment by mgage** [comment]
Hi Peter,

I’ve made a start http://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.13 <http://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.13>

still working on it however.

Take care,

Mike

**Comment by pstaabp** [comment]
I guess there aren't really any new features for this release.  It's mostly bug and security fixes, which we've tested.  For the things I'm able to test, this looks good.  

It appears that the R integration came between 2.12 and 2.13.  Does this need to be tested more?  I haven't done so and am not sure I'll personally use it, so haven't tried to set it up, but if more testing needs to be done, I can try to get it going?

**Comment by mgage** [comment]
R server is officially part of this release.  Danny has vetted it.  Danny created the 2.12-r release because some people wanted R right away.  If I have time I'll practice setting up an R-server and check it as well, but that might not happen quickly.  CodeMirror is new.  There were a couple of substantial bug fixes (for multiAnswer) and two security hole fixes.  I'm working on going through the list of pull requests.  There are also quite a few features put in to 2.12 that need continuing advertising (LTI for example) so I'll leave those messages in.

**Comment by mgage** [comment]
Danny Glin did some testing on the R-server.  I will too if I get time, although that is seeming less likely.  Officially the R-server is part of this release.  Danny created 2.12-r because some people wanted R pronto.

**Comment by pstaabp** [comment]
@dlglin  Danny, I'm trying to get the r working on my machine and yet another test case before deploying, I'm trying both a stripped-down problem with the line:
```
@pi = rserve_eval("pi");
```
as well as a problem from the Library  as stated at http://webwork.maa.org/wiki/R_in_WeBWorK. Both are generating the following error:
```
ERRORS from evaluating PG file: 
 foo at /Library/Perl/5.18/Statistics/R/IO/ParserState.pm line 56
   Died within Statistics::R::IO::ParserState::BUILD called at line 121 of /System/Library/Perl/Extras/5.18/Class/Tiny.pm
   from within Class::Tiny::Object::new called at line 668 of /Library/Perl/5.18/Statistics/R/IO/QapEncoding.pm
   from within Statistics::R::IO::QapEncoding::decode called at line 236 of /Library/Perl/5.18/Statistics/R/IO/Rserve.pm
   from within Statistics::R::IO::Rserve::eval called at line 129 of [PG]/macros/RserveClient.pl
   from within main::rserve_start called at line 144 of [PG]/macros/RserveClient.pl
   from within main::rserve_eval called at line 37 of (eval 1476)
```

I'm running this on my laptop (MacOS), but it appears that the rserve is running.  I tested it by using the RSclient package in R.   Any thoughts on this?  Also, is there a log file for the rserve?  I can't seem to find any documentation on this and wonder how to get any information on the rserve  side.  

One other piece of info:  I did get errors in testing `Statistics::R::IO`, but ignored them.  I may need to look into that first.

**Comment by dlglin** [comment]
I’ve never seen that before.  My first guess would be the same as yours: something wrong with the Statistics::R::IO install.  I’d say start there.

Danny
On Jul 14, 2017, at 1:46 PM, Peter Staab <notifications@github.com<mailto:notifications@github.com>> wrote:


@dlglin<https://github.com/dlglin> Danny, I'm trying to get the r working on my machine and yet another test case before deploying, I'm trying both a stripped-down problem with the line:

@pi = rserve_eval("pi");


as well as a problem from the Library as stated at http://webwork.maa.org/wiki/R_in_WeBWorK. Both are generating the following error:

ERRORS from evaluating PG file:
 foo at /Library/Perl/5.18/Statistics/R/IO/ParserState.pm line 56
   Died within Statistics::R::IO::ParserState::BUILD called at line 121 of /System/Library/Perl/Extras/5.18/Class/Tiny.pm
   from within Class::Tiny::Object::new called at line 668 of /Library/Perl/5.18/Statistics/R/IO/QapEncoding.pm
   from within Statistics::R::IO::QapEncoding::decode called at line 236 of /Library/Perl/5.18/Statistics/R/IO/Rserve.pm
   from within Statistics::R::IO::Rserve::eval called at line 129 of [PG]/macros/RserveClient.pl
   from within main::rserve_start called at line 144 of [PG]/macros/RserveClient.pl
   from within main::rserve_eval called at line 37 of (eval 1476)


I'm running this on my laptop (MacOS), but it appears that the rserve is running. I tested it by using the RSclient package in R. Any thoughts on this? Also, is there a log file for the rserve? I can't seem to find any documentation on this and wonder how to get any information on the rserve side.

One other piece of info: I did get errors in testing Statistics::R::IO, but ignored them. I may need to look into that first.

**Comment by pstaabp** [comment]
I was able to get the Rserve working fine as another check on that feature.

**Comment by mgage** [comment]
Looks like this is ready to merge into the master branch.  The current master node has been set to 2.12+.

The release notes for release 2.13 is at http://webwork.maa.org/wiki/Release_notes_for_WeBWorK_2.13

Most of the changes are to infrastructure, fixing bugs from 2.12 and making changes that will be used in creating release 2.14.   One infrastructure change has been to update modules used to in sending email.  The cpan module Mail::Sender has been replaced by the module Email::Sender. The former module has been deprecated for some time and is no longer supported. For most there will be little effect aside from updating the cpan module collection and setting some configuration lines in site.conf.  In some cases some experimentation will be required to adjust the configuration lines to work with the local SMTP server. 

Release 2.13 will include the modules which support the R server. It replaces the branch 2.12-r which added the R server functions to release 2.12

**Pull request merged**
