### PR TITLE
fix how many seconds are in an hour

### PR DESCRIPTION
**Pull request by Alex-Jordan**

### CODE REVIEW

**Review by drgrice1 — APPROVED** [review]
This can certainly be a hotfix!

**Review by dlglin — APPROVED** [review]
I haven't tested, but it looks correct to me.

**Comment by drgrice1** [comment]
I admit I didn't test it either.  It just seemed obviously correct, and the previous was obviously incorrect!

**Comment by drgrice1** [comment]
I am going to merge this.  Do you want to create a hotfix @Alex-Jordan?

**Pull request merged**
