### PR TITLE
Configurable modelcourses list for admin add course

### PR DESCRIPTION
**Pull request by taniwallach**
This is intended to supplement what was just done as a hot fix in https://github.com/openwebwork/webwork2/pull/1447 but to make it possible to configure a list of model courses which get prepended to the provided list.

### CODE REVIEW

**Comment by drgrice1** [comment]
I am not sure that this qualifies for a hotfix.  This adds a new feature that was not present before.  Generally that is something that should not be added after the release.

**Comment by taniwallach** [comment]
Yes and no. In the past - just about any directory in the courses directory could be used as a the source of the templates directory, as `listCourses` included them (so long as they avoided some regular expression conditions). This provides an option to optionally define selected directories (other than the fixed `modelCourse`) to be included in the list. So it reenables more of the prior functionality, but in a controlled manner.

It can certainly be put in develop instead (or dropped). Whatever the team prefers.

**Review by pstaabp — APPROVED** [review]
I think this looks good.  Technically not a hot fix, but functionality nearly equivalent and more flexible.

**Comment by drgrice1** [comment]
I see.  I suppose that could be hotfix worthy if that is something that was commonly utilized.  What do others thing on this?

**Review by drdrew42 — APPROVED** [review]
This does give an alternative for the options that were available before listCourses was modified.

**Comment by drgrice1** [comment]
Okay.  A hotfix it can be then.

**Review by drgrice1 — APPROVED** [review]
I will merge and also add it to develop.

**Pull request merged**
