### PR TITLE
remove unused latex packages

### PR DESCRIPTION
**Pull request by Alex-Jordan**
These packages can go (and one of them is causing a problem). These packages were used back with LaTeX2.09

`epsf` only provides `\epsfbox` which I find nowhere in `webwork2`, `pg`, or `OpenProblemLibrary`.

`epsfig` only provides `\psfig` which I find nowhere in `webwork2`, `pg`, or `OpenProblemLibrary`.

`pslatex` is for using PostScript fonts. We are fine with default fonts, or if not, would use something newer.

### CODE REVIEW

**Review by pstaabp — APPROVED** [review]

**Comment by drgrice1** [comment]
I have never been particularly fond of the default LaTeX fonts.  So I would prefer to use something else.  The STIX 2 fonts are nice.  They are available in the LaTeX stix2 package.

**Comment by Alex-Jordan** [comment]
Once some of the current PRs are merged, I'll be working on the hardcopy themes a bit more. I'll put in STIX 2 fonts with that.

**Comment by drgrice1** [comment]
Actually, I was thinking about it more.  Although I do much prefer the STIX 2 fonts, they don't match with the MathJax fonts.  The default LaTeX fonts match better with those.  So in the interest of making hardcopy resemble what is seen in html, it would probably be best not to switch to the STIX 2 fonts.   That is, unless MathJax can also be switched to STIX 2 fonts?

**Review by drgrice1 — APPROVED** [review]
I approve this pull request in any case.

**Pull request merged**
