### PR TITLE
add maketext calls

### PR DESCRIPTION
**Pull request by heiderich**

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
I thought this was into develop, and then I noticed it was into master right after I merged. Sigh. What is the best way to handle this now?

**Comment by heiderich** [comment]
Please excuse me for having chosen the wrong branch. It was not my intention.

**Comment by Alex-Jordan** [comment]
No problem. It's more my mistake, since I need to be very careful reviewing and merging these things. I'm going to make an executive decision and revert the merge. That will make GitHub apply another commit that removes what was added. Then I'll try to merge what was intended into develop. If I don't figure out how to do that, you can open a new PR.

**Comment by Alex-Jordan** [comment]
OK, I reverted. 

But I can't cleanly redirect your commit into develop. The branch `heiderich:maketext_calls_in_PGProblemEditor_and_SetMaker` is based off of master, not develop, and it has an additional commit in it that Mike made. I'm sure that a git master knows a clever way to handle the situation (possibly just `git rebase develop`), but the crude yet simple thing to do is if you make a new branch from develop, manually apply the same two maketext additions, and then open a new pull request.

**Comment by heiderich** [comment]
I opened a new pull request based on the develop branch: #830

**Pull request merged**
