### PR TITLE
Upgrade setOrientation

### PR DESCRIPTION
**Pull request by apizer**
Second try. Upgrade setOrientation so that the information presented matches what students see in WeBWorK 2.11

### CODE REVIEW

**Comment by apizer** [comment]
git rebase didn't work. I got 
fatal: Cannot update paths and switch to branch 'new_update_Orientation2' at the same time.
but doing things the "long' way was't bad.

**Comment by goehle** [comment]
You dont make a new branch.  It switches the current branch.  In any case this is fine.  

I hate to keep adding to this pull, but while we are messing around with this stuff...

Do we want to replace the java applet problem in setDemo; i.e. problem https://github.com/openwebwork/webwork2/blob/develop/courses.dist/modelCourse/templates/setDemo/prob6b.pg

Java applets are getting phased out and we could probably find a better demo problem to show things off.  My suggestion would be a scaffolding problem and/or a live graphics problem.

**Comment by apizer** [comment]
Maybe I should have run git fetch before git rebase so that my system knew about release-2.11.  I had to do that before my other (successful) attempt.  Oh well it worked.

I really want to keep this problem as is for historical reasons.  As it says in the site info:

9. Java example. This gives an example of incorporating a java applet which can be used experimentally to determine answers for WeBWorK questions. This example is of historical interest since it comes from the first site after Rochester, Johns Hopkins University, to use WeBWorK. It currently gives an example of what happens when a WeBWorK problem called an applet residing on a server that no longer exists. 

Adding a few additional problems would be fine.  It has been years since we did that. Set Demo basically shows what WeBWorK could do in the 90's.  Does anybody have specific problems that would be good?  Is it correct that Just-In-Time requires a separate set so you can not e.g. have a 2 problem Just-In-Time subset of a standard set?

**Comment by goehle** [comment]
Yes, Just-In-Time is a separate homework type, so you cant have two just in time homeworks. 

I think scaffolding and livegraphics are good candidates.  Others I can think of are questions involving sage or geogebra. 

As for the java applet.  I appreciate the historical reasons.  I am slightly wary of having broken things be part of the "demo" set, but I won't make a fuss if its kept in.

**Comment by goehle** [comment]
When testing this I ran across a problem that needs to be fixed.  With the addition of the "Contrib" link to modelCourse the link to "Library" isn't getting created any more.  I don't know what created it, though, or how that should be fixed.  Do you know Mike?

**Comment by goehle** [comment]
Never mind, I misunderstood how that worked. Its created by the library browser the first time you use it and that is still fine.  This pull looks good.

**Comment by jwj61** [comment]
Yes, but the model course should come with a Library link since sometimes people will use a Library problem from a set before using the library browser.

Or, I suppose one could insert a check, if looking for a problem with path starting with Library/... and it is not found, see if the Library link exists and create it if it doesn't.

**Comment by goehle** [comment]
I was thinking the same thing.  In particular I don't really like how the Contrib link is included since it has a hard coded path.  I'll put it on the list to  think about for a future pull.

**Pull request merged**
