### PR TITLE
WIRIS Editor for answer entry on WebWork

### PR DESCRIPTION
**Pull request by manuelwiris**
This changes allow user to select WIRIS Editor for answer entry.

### CODE REVIEW

**Comment by mgage** [comment]
For now do not pull this into the develop branch on github.com/openwebwork.  This pull requests announces the ability to use the WIRIS entry system (which includes handwriting recognition on iPad and iPhone!!!!!).  Pull this into your local develop branches, test it out and report back.  

This addition is commercial software which users would have to contract for separately (see license agreement) but WIRIS is committed to working with us to make their product seamlessly available to WeBWorK users. If things work out very well they may also be able to support other WW development, particularly aspects of WW which augment the usefulness of their entry system.

**Comment by mgage** [comment]
Hi Manuel,

1. to use:  run   `webwork2/bin/upgrade_admin_db.pl`
           `Added column 'useWirisEditor' to table 'user'`
2. upgrade other courses to be tested from admin webpage
3. comment out ` #    [qw(Rserve Class::Tiny IO::Handle)],` in defaults.config since these modules might not have been loaded in the standard develop branch

4. Those were the only changes I had to make to get it running.  

5. The configuration is turned on in the PG section on the CourseConfiguration page -- right next to MathView.
6. The typing portion of the app worked well on my development laptop.
7. The handwriting recognition portion of the app seems good, but my handwriting is pretty clumsy using a touch pad so it was a bit delicate to get it to recognize a 6 rather than a b. 
7. Next step is to put this up on a machine that I can reach from the web and try it out on my cell phone or and iPad. 

So far this looks really neat, thanks Manuel and WIRIS.

I'll  do some more tests and have some more comments later.

**Comment by mgage** [comment]
I have put a demo of this up at <https://devel3.webwork.rochester.edu/webwork2/fall10mth164>.  You can log in as "guest" and do the homework in that course using WIRIS input. It's interesting to use on my android phone.  It's a bit slow on my very old iPad2.  I think the ideal device would be a new tablet.

**Comment by manuelwiris** [comment]
Hi Michael, 

We are trying to access the demo course but seems there is some kind of problem. A [missing table] error appears. 

Best,

**Comment by mgage** [comment]
Hi Manuael,

I’ll turn it back on. We had a slight disaster over the weekend when an upgrade 
crashed our mysql database.  I’m still bringing things back on line.  WeBWorK
is coming back but there is still difficulty getting php installed so that I can bring back
the Moodle courses.   

Remind of the url of the course you are looking at and I’ll get it back on line sooner.

Sorry for the outage. 

Take care,

Mike

**Comment by mgage** [comment]
Hi Manuael,

I've restored the course https://devel3.webwork.rochester.edu/webwork2/fall10mth164.

It was one of the demo courses affected by our database outage so I had to rebuild it.  It may not have exactly the same questions as before.  It has the Wiris input option turned on.  This is (was) a clone of one of our multivariable calculus courses.  I could rename the course (e.g. Wiris_course) and give you greater access to it if that would help with your testing of the Wiris app. Let me know.

 I think I will try to demonstrate the option when I talk at Borough of Manhattan Community College (BMCC) next week. This kind of tablet input is particularly useful for precalculus courses.

**Pull request closed without merging**
