### PR TITLE
Fix the feedback urls for set0.  This only affects set0. 

### PR DESCRIPTION
**Pull request by drgrice1**
Very specific fix!  This fixes issue #1323.

### CODE REVIEW

**Comment by pstaabp** [comment]
I guess this is about as specific as it gets.   Funny that I'm sure this has existed for 20+ years and this is the first time.  I did a quick check for 
```
if ($params{set_id})
```
in the codebase, just to make sure there aren't other places like this.  This might be a good opportunity to double check this.

**Comment by drgrice1** [comment]
Yeah, it certainly isn't a new issue.  It is difficult to do a thorough check as set_id is also used as setID, or setId, or setName, etc.

**Review by drdrew42 — APPROVED** [review]
😂

**Comment by Alex-Jordan** [comment]
I tested this by manually applying the same edit to my production server. I don't have email running on other ones. It worked (of course). I tested sending emails from set 0, set 0 problem 1, some other set, some other set problem 1. They all came back with the right links.

**Pull request merged**
