### PR TITLE
Install Mathjax via npm

### PR DESCRIPTION
**Pull request by drgrice1**
This is a simple change that simplifies the webwork install process a bit.

### CODE REVIEW

**Review by drdrew42 — APPROVED** [review]

**Comment by drdrew42** [comment]
makes total sense

**Comment by drgrice1** [comment]
I was looking at the release notes, and realized we could remove that step quite easily.

**Comment by drdrew42** [comment]
everyone has to `npm install` for this update anyhow

**Review by Alex-Jordan — APPROVED** [review]
Looks good and works.

Testing this made me look closely at math rendering on the page. Maybe we already talked about it, but this is another thing that happens slowly now, compared to 2.15. Not because of this PR. But on 2.15 servers, math for a problem is rendered pretty fast, while now it's taking around a full second.

**Comment by drgrice1** [comment]
> Testing this made me look closely at math rendering on the page. Maybe we already talked about it, but this is another thing that happens slowly now, compared to 2.15. Not because of this PR. But on 2.15 servers, math for a problem is rendered pretty fast, while now it's taking around a full second.

That is in the difference between MathJax version 2 and 3.  The initial rendering on the page is a bit slower to kick in, but the entirety of the page being completed is much faster.  Particularly if there is quite a bit of TeX to be dealt with.  I have also noticed that rendering of things added to the page later is much faster though.  @dpvc can probably give better details.

**Comment by dpvc** [comment]
I think there are two issues at play.  First, the v3 MathJax download is larger (not is all in one file, rather than several files, so only one download, but larger).  That means MathJax can't start as quickly (but as Glenn says, it runs faster once it does).

The second affect is subtler.  Because MathJax v2 was both slower and had to wait for other files to load, it would stop periodically to allow the screen to refresh.  Version 3 doesn't do that.  So in v2, the page would refresh before Mathjax would run, and it would refresh after every few equations were processed.  That gaves the psychological impression that MathJax was operating faster than it really was.  With v3, the math doesn't show up until it is all processed, and although that occurs faster than in v2, v2 could show you some results earlier.  In fact, in some cases, with v3 you may not see the page at all until the math is processed (no flash as math first appears untypeset, then typeset), so the effect may seem longer, even though the full page is ready faster than it was in v2.

**Review by pstaabp — APPROVED** [review]
In the documentation, we could add that the `$WEBWORK_ROOT/MathJax` directory can be deleted.

**Comment by drgrice1** [comment]
Yeah, if upgrading that will not be needed anymore.

**Review by taniwallach — APPROVED** [review]
Great idea.

**Pull request merged**
