### PR TITLE
Configurable institution logo

### PR DESCRIPTION
**Pull request by Alex-Jordan**
With this, in a config chain, you can set like:

```
$institutionLogo = 'pcc_logo.png';
$institutionURL  = 'https://www.pcc.edu';
$institutionName = 'Portland Community College';
```

and then the place where we usually see the MAA logo will have a different logo, with a different href, and different alt text.

One thing an institution wants to do to customize the look of their site is have a logo link to their school. This makes that easy without having to create a new theme. The defaults are still to/for MAA, except I saw no reason not to use the larger slightlly higher res MAA logo file.

Also with this, it could be customized at the course level. So if your server hosts more than one school, some courses could have different institution logos than others.

### CODE REVIEW

**Review by pstaabp — APPROVED** [review]
Works well and looks good.

**Review by pstaabp — CHANGES_REQUESTED** [review]
Actually, just noticed that the image I put in the `htdocs/images` directory is now tracked with git.  Perhaps, make a directory in `htdocs/images` to store these and put the directory contents in `.gitignore`.

**Comment by drgrice1** [comment]
I would like the image to be able to be placed in a custom theme directory rather than in the images directory.

**Comment by Alex-Jordan** [comment]
Does an images folder in the math4 theme make sense?

If so, should I move the MAA logo and WeBWorK logo in there? Tracked by git.

**Comment by drgrice1** [comment]
I think that makes sense.  You could say that they are part of the theme.  Then we can move closer to just being able to delete the images directory.  Very little of what is in there is used.

**Comment by Alex-Jordan** [comment]
OK, now there is an `images` folder in `math4`. And symlinks to that folder from `math4-green` and `math4-red`.

I either removed or deleted the various log image files that relate to this form `htdocs/images`.

**Comment by taniwallach** [comment]
@Alex-Jordan: I think we wanted to use `.gitconfig` to have Git ignore changes in these images folders.
Is there anything else we need to fix?

**Comment by Alex-Jordan** [comment]
@taniwallach I don't recall that there was anything more to do. I just committed that change to `.gitignore` though.

**Review by taniwallach — APPROVED** [review]
Tested and works. Having the extra line in `.gitignore` helps as it should help keep local image files from ending up in the main repository.
I think this is ready to merge.
@drgrice1 - Sorry this also has `maketext` calls.

**Comment by taniwallach** [comment]
@pstaabp - With the `.gitignore` I think @Alex-Jordan fixed your remaining reservation.

**Comment by Alex-Jordan** [comment]
Stand by. Glenn and I think that the `.gitignore` addition should not use a wildcard and go directly through `math4`, `math4-green`, and `math4-red`. I'll make that change soon.

**Comment by Alex-Jordan** [comment]
OK, now this has each of `math4`, `math4-green`, and `math4-red` with an honest images folder. There are honest logo files in `math4/images`, and symlinks to them in the other two `images` folders. All of that is part of the distribution.

But then anything inside the three `images/` folders is in `.gitignore`.

So I think this will be good for @pstaabp  and anyone else to make another review.

**Review by drgrice1 — APPROVED** [review]
This looks good and is a good improvement to the theme system.

**Comment by drgrice1** [comment]
Why did I add the "Do not merge yet" label to this?  Github says I did that, but I don't remember doing it or why.

**Comment by Alex-Jordan** [comment]
> Why did I add the "Do not merge yet" label to this? Github says I did that, but I don't remember doing it or why.

Could just be an errant GitHub click. 

The choice I made for which things are sylinks and which things are in `.gitignore` is something @pstaabp may want to think about before approving.

**Review by pstaabp — APPROVED** [review]
This looks good to me now.

**Pull request merged**
