### PR TITLE
Fix the problem urls in the emails sent using the "E-Mail Instructor" feedback page

### PR DESCRIPTION
**Pull request by drgrice1**
This was introduced in pull request #986.

That pull request switched from obtaining the set and problem ids cached
in the WeBWorK::ContentGenerator::Problem object to attempting to find
the set and problem ids from the url parameters.  The problem is that
the feedback page does not have those url parameters.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Thanks Glenn, that was fast. I'll review and test Monday.

**Comment by drdrew42** [comment]
wow, yeah - I started working on a fix without realizing you'd already put this out. This looks good, thanks for cleaning up my mess!

**Review by drdrew42 — APPROVED** [review]

**Review by Alex-Jordan — APPROVED** [review]
Works as advertised.

**Comment by Alex-Jordan** [comment]
I'm going to merge now. It's working on my server and @drdrew42 approves. That seems like enough.

**Pull request merged**
