### PR TITLE
Clean up a warning about uninitialized  for course_info.txt

### PR DESCRIPTION
**Pull request by Alex-Jordan**

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Do I submit a pull request to develop as well, or will 2.11 be merged back into develop?

**Comment by Alex-Jordan** [comment]
This is the continuation of https://github.com/openwebwork/webwork2/pull/635

**Comment by goehle** [comment]
2.11 will get merged back into develop.

**Comment by goehle** [comment]
Works for me.

**Pull request merged**
