### PR TITLE
shibboleth: use proxy-supplied request header

### LINKED ISSUE #2286: Feature - Shibboleth authentication for WeBWorK 2.18
Hi all! We're planning to upgrade to WeBWorK 2.18 in our environment and we are planning to continue using Shibboleth authentication.

Don't worry! We'll figure out how to make it work (for our own documentation) and then share that back with the community. We are confident in our ability to update the existing Shibboleth integration file for WeBWorK 2.18, especially as we already support a few Shibboleth-adjacent login plugins. The goal will be to keep it as simple as possible to minimize any maintenance concerns (for everyone involved, us included).

For now, please assign this issue to me (@jrchamp) and my colleague (@smbader). If someone, such as @jmacdone or @xcompass, get to it before we can, even better. Teamwork! :heart:

### PR DESCRIPTION
**Pull request by jrchamp**
Mojolicious does not have access to the environment variables supplied by the httpd module which connects to the Shibboleth service provider. Instead, using httpd as a reverse proxy allows for us to provide the user_id via a request header. For security, we forcibly unset any pre-existing request header with the name we plan to use and then only set the request header when it is available from the original httpd environment variable.

```apacheconf
<Location "/">
        # Shibboleth lazy-loading sessions.
        AuthType shibboleth
        ShibRequestSetting requireSession 0
        require shibboleth

        RequestHeader unset eppn
        RequestHeader set eppn %{eppn}e env=eppn
</Location>
```

If you have any questions, concerns or suggestions, please let me know.

Fixes #2286

### CODE REVIEW

**Review by drgrice1 — APPROVED** [review]
This looks good to me.  I have no way to test this, but I will trust that it works for you.  It can't be any worse than the current state of affairs!

**Review by pstaabp — APPROVED** [review]
I can't test it, but I'll approve it.

**Comment by jrchamp** [comment]
@xcompass @juu7nitw23 In case you have time to test this update for the Shibboleth authen in the Mojolicious versions of WeBWorK.

**Comment by juu7nitw23** [comment]
Thanks.  I will try to see if I can test it next week

**Comment by drgrice1** [comment]
We are just going to merge this.  If further changes are made, a new pull request can be made.

**Pull request merged**
