### PR TITLE
make achievement items have effect on reduced scoring date

### PR DESCRIPTION
**Pull request by Alex-Jordan**
Currently if I have a "full credit" date (aka "reduced credit" date) in the middle of the term, with the "close" date at the end of the term, then using any item that extends a due date just pushes back the "close" date. The student feels cheated that the "full credit" date has not also been moved. These edits change that.

### CODE REVIEW

**Comment by drgrice1** [comment]
It is not really the proper github flow of things to put your pull request branches directly into the main github repository for the project.  That is what your individual fork is for.  The webwork github repository is getting cluttered.  We now have Alex-Jordan-patch-1, goehly-uploaded-message, and this branch that I don't think belong there.

**Comment by Alex-Jordan** [comment]
Sorry, I thought I was editing in my own GitHub fork. I find it easy to get mixed up, and GitHub has moved me to a different fork (probably because of my own user error.)

**Comment by drgrice1** [comment]
I see.  It isn't a big deal.  It just adds clutter.

**Comment by drdrew42** [comment]
I am not able to test anything for a bit, but is there any possible conflict here for courses that do not have reduced scoring turned on? 

Courses with reduced scoring _disabled_ will have NULL values for `reduced_scoring_date`. What will perl think of adding NULL + 86400?

**Comment by Alex-Jordan** [comment]
I added conditionals to check if `$set->reduced_scoring_date()` is already defined before trying to add time to it.

**Comment by mgage** [comment]
I have trouble testing this because I don't immediately know how to artificially trigger an achievement.  However the code looks sound and any difficulties that are caused will be cosmetic and fairly easy to track down.

**Comment by Alex-Jordan** [comment]
Thanks Mike, and I'll delete the branch this was on. I'll be more careful to create these GitHub patch branches within my own fork.

**Pull request merged**
