### PR TITLE
Main add sponsor

### PR DESCRIPTION
**Pull request by mgage**
Add sponsor button to CourseAdmin page.

Added modification to formatting to make it easier to add material to the display_registration_form subroutine.
I didn't have a clean WeBWorK-2.17 branch to start with so I hope that the provenance of this commit is not too messed up.

### CODE REVIEW

**Comment by pstaabp** [comment]
Works well.  Here's what the button looks like to me: 

image

Not as clean looking at the bootstrap variety and seems overkill to make an iframe to do this.  How about just make a button with a link to the sponsor page?

**Comment by pstaabp** [comment]
Also, to test, remove `/opt/webwork/courses/admin/registered_2.17` and reopen the course admin page.

**Comment by drgrice1** [comment]
@mgage:  I put in a pull request to your branch that cleans things up quite a bit.

**Review by drgrice1 — APPROVED** [review]
Looks good now.

**Review by pstaabp — APPROVED** [review]

**Pull request merged**
