### PR TITLE
Refactor FormatRenderedProblem.pm and WebworkClient

### PR DESCRIPTION
**Pull request by mgage**
Minor (and possibly redundant) fixes to renderViaXMLRPC.pm and RenderProblem.pm

### CODE REVIEW

**Comment by mgage** [comment]
Should be possible to merge into WW-2.15.  @Alex-Jordan  It needs testing to make sure that it doesn't interfere with any PreTeXt operations

**Comment by Alex-Jordan** [comment]
Is there by chance a public server up with this branch running? If so, I could just use that to test if it is working with PreTeXt. I only need a course, and a user account with at least login_proctor permissions. Possibly I could set up a test server, but it would take significantly more time given some limitations I have right now.

**Comment by mgage** [comment]
Hi Alex.   I've set the software version running on demo.webwork.rochester.edu to this PR.
There is a course daemon_course with a user daemon and the usual password and level 2 permissions.  See if that works.  Thanks for helping out.

**Comment by Alex-Jordan** [comment]
OK, I tested on the PTX sample article that stress tests WeBWorK integration, and there is no change from this PR.

However, there is a different issue this move to 2.15 is bringing to the fore. It is a pg issue, so I will open an issue there for discussion.

**Comment by mgage** [comment]
@taniwallach   Tani could you check that sendXMLRPC.pl works properly on your installation? I think this is ready to merge.

**Comment by taniwallach** [comment]
The `use JSON` is fixed in https://github.com/mgage/webwork2/pull/31

Thanks for fixing to `my $local_psvn` - I had picked up on that yesterday, but did not have time to comment about it.

**Comment by mgage** [comment]
Thanks — the json format got lost somewhere along the way.  I’ve got it on my laptop but let’s just put it into this 2.15 version so it doesn’t
get lost.

Take care,

Mike


On Sep 20, 2019, at 10:06 AM, Nathan Wallach <notifications@github.com<mailto:notifications@github.com>> wrote:


The use JSON is fixed in mgage#31<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mgage_webwork2_pull_31&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=C6Pt5AGtImanmAdcooarL-JZO8M5dSFPfs3VweYXYkE&m=vDkD-0VCq21S0zfS5y9RgbLYFUflq1np_YiM8edAV5w&s=8N7MruDbEIjN2sJX8cLU-QzN6lUi6LsZnR2pqlNMcbg&e=>

Thanks for fixing to my $local_psvn - I had picked up on that yesterday, but did not have time to comment about it.

**Comment by mgage** [comment]
Hmmmm.  @taniwallach   Your "changes requested" entry is still around.  Is that still valid after the recent updating? It seems that most of those changes have already been incorporated. I don't have time to do a complete check while still at the conference. (I'll be home tomorrow.) but I don't want to merge this is we still have some stale code in the FormatRenderedProblem file.

I haven't figured out how to get rid of the "changes requested" entry or mark it resolved but I don't want to try to merge until I'm sure it's ok.

**Comment by taniwallach** [comment]
> Hmmmm. @taniwallach Your "changes requested" entry is still around. Is that still valid after the recent updating? It seems that most of those changes have already been incorporated. 
>  ...
>  but I don't want to merge this is we still have some stale code in the FormatRenderedProblem file.
> 
> I haven't figured out how to get rid of the "changes requested" entry or mark it resolved but I don't want to try to merge until I'm sure it's ok.

The "changes request" seems to need to be manually replaced. The fix you just committed was exactly what was needed. 

What stale code are you referring to?

**Comment by mgage** [comment]
I wasn't referring to specific stale code, but there have been a few PR that have been outstanding long enough that in some cases I've found patches I'd forgotten about on my machine or in other branches.   I think this one is ok.

**Pull request merged**
