### PR TITLE
Update instructor help files (team effort?)

### PR DESCRIPTION
**Pull request by drgrice1**
This is hopefully a team effort pull request to update these help files.  If you are a maintainer, then you can push directly to this branch.  Please do not force push, and remember to pull frequently to get changes others may have pushed since you last worked on it.  If you are not a maintainer, then you will need to put in a pull request to this branch to get your changes in.

Of course, feel free to discuss here.

Bare bones help files have been added for pages that do not already have help files.  These should be improved to actually say something useful. Existing help files should be reviewed and improved as well.
    
When updating these help files remember two things.  These are not shown to students, and these are only available when the page that the help is for is already visible.  The second things means that these help files should not just list the content of the page that is already visible for the user.  That is pointless.  Instead the help files should describe more detailed usage of the page, and most importantly, things that are not intuitive from the layout of the page to begin with.

The following is a list of the existing help files.  

If you are working on a particular help file, put your initials by the file to make note of your work and prevent conflict.

- [x] Achievements.html.ep
- [x] Grades.html.ep (JS)
- [x] Hardcopy.html.ep (PS)
- [x] InstructorAchievementEditor.html.ep (JS)
- [x] InstructorAchievementList.html.ep (PS and JS)
- [x] InstructorAchievementUserEditor.html.ep (JS)
- [x] InstructorAddUsers.html.ep (PS)
- [x] InstructorAssigner.html.ep (PS)
- [x] InstructorConfig.html.ep
- [x] InstructorFileManager.html.ep (PS)
- [x] InstructorIndex.html.ep
- [x] instructor_links.html.ep
- [x] InstructorLTIUpdate.html.ep (JS)
- [x] InstructorPGProblemEditor.html.ep
- [x] InstructorProblemGrader.html.ep
- [x] InstructorProblemSetDetail.html.ep
- [x] InstructorProblemSetList.html.ep (PS)
- [x] InstructorScoring.html.ep (PS)
- [x] InstructorSendMail.html.ep (JS)
- [x] InstructorSetMaker.html.ep (PS)
- [x] InstructorShowAnswers.html.ep
- [x] InstructorStats.html.ep (JS)
- [x] InstructorStudentProgress.html.ep (JS)
- [x] InstructorUserDetail.html.ep
- [x] InstructorUserList.html.ep
- [x] InstructorUsersAssignedToSet.html.ep
- [x] Levels.html.ep
- [x] Options.html.ep
- [x] ProblemSets.html.ep

### CODE REVIEW

**Comment by somiaj** [comment]
What about the 'Show/Hide Site Description' buttons still floating around on some pages (appears to be on the UserList, AchievementList, ProblemSetList, and ShowAnswers/instructor-selctors pages). Seems these are older descriptions (and give help information) that probably should just be in the help page.

Should we remove these and just put any relevant info in the help pages instead?

**Comment by drgrice1** [comment]
I agree.  I think that if there is anything in the `Show/Hide Site Description` that is missing from the help template, then it should be moved to the help template.  Then the `Show/Hide Site Description` should be eliminated.

**Comment by pstaabp** [comment]
I see in a couple pages that there is HTML embedded inside a `maketext` call.  I'm guessing we don't want this. For example
```
maketext('If you upload your file on the web with the name: <code>report_grades_data.csv</code> and also...
```
If we switch this to 
```
maketext('If you upload your file on the web with the name: ') . <code>report_grades_data.csv</code> . maketext('and also ...)
```
this will generate fragments in the maketext code to translate.  What's the best way to handle this?

**Comment by drgrice1** [comment]
In general it is okay to have html in a maketext call.  In fact it is what should be done in some cases.  See lines 31-36 of InstructorFileManager.html.ep for example.  That contains the sentence, "To view the format for <strong>ClassList files</strong> see the <a [_1]>ClassList specification</a> or download the demoCourse.lst file and use it as a model."  Translators are expected to know basic html and be able to deal with that correctly.  The point is that the words inside the html tags are part of the sentence, and need to be translated.  The translator is expected to translate those parts and fit them into the sentence structure of the translated language.  The `href` attribute of the `a` tag is interpolated into the `a` tag, and the translator should know to include the `[_1]` as it is it was.  Of course the `href` and its value should not be translated.

In the case of the `code` tag you are referencing, the contents should not be translated, and so the entire html tag and its contents should be interpolated.  I missed that in InstructorScoring.html.ep.

There is another case in `InstructorStats.html.ep`.  That one could be done in the same way, but even better would be to remove the equation given in pseudo variables, and replace that with a proper sentence explanation.  That column actually has a popup (added by @somiaj) in the page with a better sentence structure.

**Comment by pstaabp** [comment]
@somiaj If you're making changes, please put your initials on the files.  And then when finished, we should check the boxes.

**Comment by drgrice1** [comment]
@pstaabp: @somiaj does not have the permissions to make changes to the messages in this conversation.  He made a pull request to the branch which I merged.

@somiaj:  You can still add a comment here stating the files that you are working on.

**Comment by pstaabp** [comment]
@drgrice1 You used an `=%>` instead of `%> on some of the perl interpolation in the mojo templates.  I was looking through the documentation at [https://docs.mojolicious.org/Mojo/Template](https://docs.mojolicious.org/Mojo/Template) and haven't seen any use of the `=%>`.  Just curious.

**Comment by pstaabp** [comment]
Never mind, just searched the documentation.  It's a trim whitespace.  Didn't look carefully enough.

**Comment by somiaj** [comment]
Just submitted a PR that updates the `Grades.html.ep`, `InstructorStats.html.ep`, `InstructorStudentProgress.html.ep`, and `InstructoLTIUpdate.html.ep` pages.  In addition I cleaned up the pages a bit too by removing text on the page that was essentially help. I shortened the h1 title length on the student progress page to be more in line with the stats page. I fixed an issue where the number of incorrect attempts was not being displayed on a per problem grade page.

I also added another help bubble the Problems header on the tables with per problem grades that give help on what the two numbers represent. I put the help here since it should also be visible to students who view the grades page.

**Comment by somiaj** [comment]
I added a pull request to update `InstructorSendEmail` to match the changes in #1986.

**Comment by drgrice1** [comment]
They are good. I didn't check closely to see what files have been dealt with.  I checked them now.

**Comment by drgrice1** [comment]
I think that at this point we have decent help for all pages.  So this is ready to be merged.

**Review by drdrew42 — APPROVED** [review]

**Comment by drgrice1** [comment]
I am going to go ahead and merge this.  Thanks to @somiaj and @pstaabp for your help in getting these files updated.

**Pull request merged**
